Add gatekeeper method
shakacode/shakapacker pull request #102
Opened 2022-04-14 03:46 UTC by Judahmeek

Enables the use of a webpacker.yml config value as a complement to `ENV["WEBPACKER_PRECOMPILE"]`

2022-04-14 09:00 UTC, justin808 commented on lib/webpacker/commands.rb
> +    return undefined unless config.asset_precompile?
1. Default should be true
2. We can read the ENV value here. It's awkward to have 3 spots: https://github.com/shakacode/shakapacker/search?q=WEBPACKER_PRECOMPILE
3. Any downsides to using `send`?

@tomdracz Thoughts?

2022-04-14 10:54 UTC, tomdracz commented on lib/webpacker/commands.rb
> +    return undefined unless config.asset_precompile?
My first instinct would be probably just changing all the places where we call stuff like:

```
skip_webpacker_clobber = %w(no false n f).include?(ENV["WEBPACKER_PRECOMPILE"])
```

to something like `skip_webpacker = !Webpacker.config.asset_precompile?`

And then define `asset_precompile?` to either fetch value from env or config. Default should be true.

Will need some docs, at the moment behaviour  of setting `WEBPACKER_COMPILE` is completely undocumented

2022-04-14 10:56 UTC, tomdracz commented on lib/webpacker/commands.rb
> +    return undefined unless config.asset_precompile?
Also maybe  changing `asset_precompile?` -> `enhance_asset_precompile?` to better convey what it is meant to do

2022-04-15 00:21 UTC, justin808 commented on lib/webpacker/commands.rb
> +    return undefined unless config.asset_precompile?
@tomdracz should we can generalize so that the config allows being overridden by ENV values?

I agree on the better naming, which can correspond to the ENV key, like `WEBPACKER_ENHANCE_ASSETS_PRECOMPILE`

and that maps to `Webpacker.config.enhance_assets_precompile`

So we strip out the leading `WEBPACKER_` from the env keys.

2022-04-15 00:43 UTC, justin808 commented on lib/webpacker/commands.rb
> +    return undefined unless config.asset_precompile?
We'll change places that look like this to use a common method, called `webpacker_enhance_precompile`, "require" in a sibling file. That method will use simple YAML, so not requiring that webpacker be initialized at this point.

```
# Compile packs after we've compiled all other assets during precompilation
skip_webpacker_precompile = %w(no false n f).include?(ENV["WEBPACKER_PRECOMPILE"])
```

2022-04-15 01:07 UTC, Judahmeek commented on lib/webpacker/commands.rb
> +    return undefined unless config.asset_precompile?
@justin808 Webpacker is already initialized here: https://github.com/shakacode/shakapacker/blob/master/lib/tasks/webpacker/verify_config.rake#L6

2022-04-15 01:11 UTC, justin808 commented on lib/tasks/webpacker/clean.rake
> +skip_webpacker_clean = %w(no false n f).include?(ENV["WEBPACKER_PRECOMPILE"]) || Webpacker.config.dont_enhance_asset_precompile
Let's dry up this logic

2022-04-15 01:11 UTC, justin808 commented on lib/webpacker/configuration.rb
> +    fetch(:dont_enhance_asset_precompile)
change to 

`skip_webpacker_precompile` with the default being false.

2022-04-15 01:11 UTC, justin808 commented on lib/webpacker/configuration.rb
> +    fetch(:dont_enhance_asset_precompile)
I think we can have this logic in here

```ruby
%w(no false n f).include?(ENV["WEBPACKER_PRECOMPILE"])
```

2022-04-15 01:35 UTC, justin808 commented on lib/webpacker/configuration.rb
> +  def skip_webpacker_precompile?
Let's rename this to `webpacker_precompile` so that we match up the ENV.

2022-04-15 01:49 UTC, justin808 commented on lib/webpacker/configuration.rb
> +  end
1. Let's have a couple of tests for this logic
2. How about

```ruby
def webpacker_precompile?
  # ENV of false takes precedence
  return false if %w(no false n f).include?(ENV["WEBPACKER_PRECOMPILE"])
  return true if %w(yes true t).include?(ENV["WEBPACKER_PRECOMPILE"])

  fetch(:webpacker_precompile)
end
```

2022-04-15 01:49 UTC, justin808 commented on lib/webpacker/configuration.rb
> +  end
@tomdracz thoughts?

2022-04-15 01:51 UTC, justin808 commented on lib/webpacker/configuration.rb
> +  end
above could be abstracted to take 

```ruby
def env_or_yml_boolean_value(key)
  return false if %w(no false n f).include?(ENV[key.upcase])
  return true if %w(yes true t).include?(ENV[key.upcase])

  fetch(key)
end
```

```ruby
def webpacker_precompile?
  env_or_yml_boolean_value(:webpacker_precompile)
end
```

2022-04-15 03:08 UTC, justin808 commented on test/configuration_test.rb
> +    end
Needs to test the config file setting, if possible.

2022-04-15 07:57 UTC, tomdracz commented on lib/webpacker/configuration.rb
> +  end
Agree, makes this bit nicer

2022-04-15 07:58 UTC, tomdracz commented on test/configuration_test.rb
> +    end
Would be good, might be as simple as setting different value for one of the envs in the test app for now

2022-04-15 08:01 UTC, tomdracz requested changes
One note for me and +1 on bits noted by @justin808

2022-04-15 08:01 UTC, tomdracz commented on lib/install/config/webpacker.yml
> +  webpacker_precompile: true
Let's add some inline conmment here to clarify usage and update the readme section at https://github.com/shakacode/shakapacker/blob/master/README.md#deployment - it talks about how webpacker enhances the rails precompile task, need to note how this setting will change this behaviour

2022-04-18 08:49 UTC, justin808 commented
@Judahmeek any ETA for getting this completed?

2022-04-20 07:41 UTC, justin808 commented on lib/install/config/webpacker.yml
> +  webpacker_precompile: true
@Judahmeek please do this and it's ready to merge.

2022-04-20 08:45 UTC, tomdracz commented on lib/install/config/webpacker.yml
> +  webpacker_precompile: true
Yup, that one and rebase with main to sort out Rubocop errors and we're good to go

2022-04-20 18:14 UTC, Judahmeek commented on lib/install/config/webpacker.yml
> +  webpacker_precompile: true
Done

2022-04-20 20:05 UTC, tomdracz approved these changes
LGTM

2022-04-22 09:08 UTC, justin808 requested changes

2022-04-22 09:08 UTC, justin808 commented on lib/install/config/webpacker.yml
> +  webpacker_precompile: true
^^^^

https://github.com/shakacode/shakapacker#deployment

???

2022-04-23 08:53 UTC, merged