Added React integration
shakacode/shakapacker pull request #110
Opened 2022-04-25 12:55 UTC by jameshibbard

Adds docs on React integration (as discussed [here](https://github.com/shakacode/shakapacker/issues/92#issuecomment-1101227999)).

2022-05-07 01:34 UTC, justin808 requested changes
Exciting. A couple suggestions!

2022-05-07 01:34 UTC, justin808 commented on docs/react.md
> +npm i -g yarn
`asdf` and `yvm` are other ways.

Let's say, "for example"

2022-05-07 01:34 UTC, justin808 commented on docs/react.md
> +10. Hit: <http://localhost:3000/site/index>
Is using `<URL>` better? Do we need the `<`?

2022-05-07 13:37 UTC, jameshibbard commented on docs/react.md
> +npm i -g yarn
Sure. I updated the PR.

2022-05-07 13:39 UTC, jameshibbard commented on docs/react.md
> +10. Hit: <http://localhost:3000/site/index>
It's a shortcut style for creating “automatic” links for URLs, which means you can show the text of the URL and also have it be a clickable link. See [here](https://daringfireball.net/projects/markdown/syntax#autolink). 

Happy to remove if it's not needed.

2022-05-17 09:07 UTC, tomdracz approved these changes
LGTM, nice work @jameshibbard

2022-05-17 09:14 UTC, merged