Remove `assets:precompile` task enhancement
shakacode/shakapacker pull request #131
Opened 2022-05-25 13:40 UTC by jherdman

Move this responsibility to the host application

Resolves #125

2022-05-25 15:03 UTC, jherdman commented
Updated as requested.

2022-05-25 15:18 UTC, tomdracz requested changes
Two more changes and we're good to go @jherdman

2022-05-25 15:18 UTC, tomdracz commented on lib/tasks/webpacker/compile.rake
> +  Rake::Task.define_task("assets:precompile" => ["webpacker:compile"])
We should still use `enhance_assets_precompile` here so we need something like:

```
  if Rake::Task.task_defined?("assets:precompile")
    enhance_assets_precompile
  else
    Rake::Task.define_task("assets:precompile" => ["webpacker:compile"])
  end
```

2022-05-25 15:18 UTC, tomdracz commented on lib/tasks/webpacker/compile.rake
> -end
Don't need the `yarn_install_available?` but we should keep the `enhance_assets_precompile` method, just without the deps so something like:

```
def enhance_assets_precompile
  Rake::Task["assets:precompile"].enhance do |task|
    prefix = task.name.split(/#|assets:precompile/).first

    Rake::Task["#{prefix}webpacker:compile"].invoke
  end
end
```

2022-05-25 17:19 UTC, jherdman commented on lib/tasks/webpacker/compile.rake
> -end
smh... oops!

2022-05-25 17:19 UTC, jherdman commented
Fixed. Apologies for the bumps along the way on this one.

2022-05-26 06:50 UTC, justin808 commented
LGTM

2022-05-26 06:50 UTC, justin808 approved these changes

2022-05-26 08:10 UTC, tomdracz commented
> I think we can remove this too? https://github.com/shakacode/shakapacker/blob/master/lib/install/bin/yarn

This is still used during setup and diagnostic check so good to remain. All looks good now, merging! Thanks @jherdman

2022-05-26 08:10 UTC, merged

2022-06-07 03:41 UTC, Judahmeek commented
@tomdracz I don't understand the point of this PR.

Isn't `yarn install` is a no-op if `node_modules` is already up to date?