Add Append StyleSheet Pack Tag Helper
shakacode/shakapacker pull request #144
Opened 2022-06-10 17:24 UTC by pulkitkkr

## Summary
To add stylesheets for the new filesystem-based Component Registry API, We need a stylesheet to append helper. This PR Adds the` stylesheet_append_tag` helper to Shakapacker Codebase

2022-06-12 08:44 UTC, tomdracz requested changes

2022-06-12 08:44 UTC, tomdracz commented on lib/webpacker/helper.rb
> +      raise "To prevent duplicated stylesheet on the page, you should call stylesheet_pack_tag only once on the page. " \
I would rather not bring this raise back at this point. Duplicate stylesheets are less problematic and I don't want to bring in a breaking change for any users that relied on this raise not being here.

We'd be shipping this PR in a minor release so avoiding breaking changes is preferable.

2022-06-12 08:44 UTC, tomdracz commented on lib/webpacker/helper.rb
> +  def append_stylesheet_pack_tag(*names)
Think we need more than just names here. If you look at original issue around multiple pack tags, one of the requests was supporting different "media" attributes.
Wondering if we should queue up files based on media attribute in the same way we queue and organise js packs on defer attr

2022-06-13 08:50 UTC, justin808 commented
@pulkitkkr you have CI issues.

2022-06-14 19:56 UTC, pulkitkkr commented on lib/webpacker/helper.rb
> +      raise "To prevent duplicated stylesheet on the page, you should call stylesheet_pack_tag only once on the page. " \
Hey @tomdracz! I am removing the raise for now :) But Still keeping it as a warning in logs :)

2022-06-14 20:05 UTC, pulkitkkr commented on lib/webpacker/helper.rb
> +  def append_stylesheet_pack_tag(*names)
We can Queue Up the files based on media attributes as a separate Feature Pull Request as, unlike deferred, it's not a boolean value and can have  `and`, `not` or a comma.

Example: `media="screen and (max-aspect-ratio:16/9)"`.

2022-06-15 09:21 UTC, justin808 commented on lib/webpacker/helper.rb
> +  def append_stylesheet_pack_tag(*names)
@tomdracz I'm not convinced how many people would need both the flexibility of the `append_stylesheet_pack_tag` with different `media` attributes.

Let's wait for feedback. 

If necessary, we release an update where the `*names` arg can be either:

1. String of the pack name
2. Hash, where the keys are the `media` and the values are arrays of packs.

@tomdracz do you agree that this would be a backwards compatible update if needed?

@pulkitkkr are we ready to merge and release this one?

2022-06-15 09:21 UTC, justin808 commented
@pulkitkkr we need:

1. Tests
2. Documentation

2022-06-16 08:55 UTC, tomdracz reviewed
Couple more comments added

2022-06-16 08:55 UTC, tomdracz commented on lib/webpacker/helper.rb
> +    appended_packs = available_sources_from_manifest_entrypoints(@stylesheet_pack_tag_queue || [], type: :stylesheet)
Does this need any deduplication? Can names passed and what's in `@stylesheet_pack_tag_queue` reference the same files that we would load twice?

2022-06-16 08:55 UTC, tomdracz commented on lib/webpacker/helper.rb
> +      names.map { |name| current_webpacker_instance.manifest.lookup_pack_with_chunks(name.to_s, type: type) }.flatten.compact.uniq
@pulkitkkr What's the rationale for adding this? Why would we use non-raising method that does not indicate pack missing?

2022-06-16 08:56 UTC, tomdracz commented on lib/webpacker/helper.rb
> +  def append_stylesheet_pack_tag(*names)
@justin808 If I remember correctly we've removed the raise in the first place to support different `media` attrs. Agree that if we've got that in place, then having it in `append_` helper is less crucial.

The update if needed should be backwards-compatible, yes

2022-06-17 14:18 UTC, pulkitkkr commented on lib/webpacker/helper.rb
> +      names.map { |name| current_webpacker_instance.manifest.lookup_pack_with_chunks(name.to_s, type: type) }.flatten.compact.uniq
@tomdracz We are introducing a new feature to `react_on_rails` that automatically loads the packs associated with the requested component.

Eg: Developer used `react_component("MyComponent", props )`

This will automatically load, `generated/MyComponent` pack using `append_javascript_pack` and `append_stylesheet_pack`

While testing this on one of the projects, we discovered there were few component packs with `js` only, i.e. `No stylesheets.` We want to use a non-error-raising lookup to handle such a scenario.

2022-06-17 14:22 UTC, pulkitkkr commented on lib/webpacker/helper.rb
> +    appended_packs = available_sources_from_manifest_entrypoints(@stylesheet_pack_tag_queue || [], type: :stylesheet)
That's a good catch, Handled it by using `stylesheet_link_tag(*(requested_packs | appended_packs), **options)` now.

2022-06-17 20:32 UTC, pulkitkkr commented on lib/webpacker/helper.rb
> +  def append_stylesheet_pack_tag(*names)
@tomdracz should we document the ordering for `appended_packs` and `requested_packs` ?

2022-06-24 02:45 UTC, justin808 requested changes

2022-06-24 02:45 UTC, justin808 commented on README.md
> +
The fully copy/paste replace is a bit awkward.

> All the magic of splitting up the code was automatic!

Maybe: 
`All the magic of splitting up the CSS was automatic!`

However, I think the docs can be more concise by discussing both helpers together.

Plus the docs for the `append_stylesheet_pack_tag` and `stylesheet_pack_tag` should mention the media type issue.

2022-06-24 02:45 UTC, justin808 commented on lib/webpacker/helper.rb
> +  def append_stylesheet_pack_tag(*names)
@pulkitkkr we need to document what happens when this happens:

```erb
<%= stylesheet_pack_tag "application" %>
<%= stylesheet_pack_tag "print", media: "print" %>
```


See https://github.com/shakacode/shakapacker/issues/39#issuecomment-1065035552

2022-06-24 02:45 UTC, justin808 commented on test/helper_test.rb
> +  end
Tests don't address:

* stylesheet_pack_tag can be called multiple times with different media attributes, while javascript_pack_tag can be called only once.

2022-06-29 22:48 UTC, pulkitkkr commented on test/helper_test.rb
> +  end
Added a test `test_multiple_stylesheet_pack_with_different_media_attr` and for `javascript_pack_tag ` we already have test `test_javascript_pack_tag_multiple_invocations`

2022-06-29 23:05 UTC, pulkitkkr commented on lib/webpacker/helper.rb
> +  def append_stylesheet_pack_tag(*names)
We already have : 
```
While this also generally applies to `stylesheet_pack_tag`, you may use multiple calls to stylesheet_pack_tag if, say, you require multiple <style> tags for different output media:

``` erb
<%= stylesheet_pack_tag 'application', media: 'screen' %>
<%= stylesheet_pack_tag 'print', media: 'print' %>
```

2022-06-30 15:18 UTC, alexeyr commented on test/helper_test.rb
> +  end
Is `assert_nothing_raised` enough there? Can we also test what happens?

2022-06-30 15:21 UTC, alexeyr commented on test/helper_test.rb
> +  end
(and possibly both with the same and different stylesheet names).

2022-06-30 15:22 UTC, pulkitkkr commented on test/helper_test.rb
> +  end
@alexeyr We already have a one for different names `test_stylesheet_pack_tag_multiple_invocations_are_allowed`

2022-06-30 15:22 UTC, alexeyr commented on README.md
> +
Trivial, but this extra line was probably added accidentally. If you do change tests, may as well remove it.

2022-06-30 15:25 UTC, alexeyr commented on test/helper_test.rb
> +  end
I meant with different names _and_ different media attributes, which that test doesn't do.

2022-06-30 15:31 UTC, pulkitkkr commented on README.md
> +
Removed it! My bad.

2022-06-30 15:32 UTC, pulkitkkr commented on test/helper_test.rb
> +  end
Updated The Test to handle this scenario :)

2022-06-30 15:38 UTC, alexeyr commented on README.md
>  Thus, you can distribute the logic of what packs are needed for any route. All the magic of splitting up the code was automatic!
Actually, there is something left over from @justin808's comments here: "splitting up code _and CSS_"

2022-06-30 15:38 UTC, alexeyr commented on README.md
>  Thus, you can distribute the logic of what packs are needed for any route. All the magic of splitting up the code was automatic!
or "code and stylesheets"

2022-06-30 15:40 UTC, pulkitkkr commented on README.md
>  Thus, you can distribute the logic of what packs are needed for any route. All the magic of splitting up the code was automatic!
Updated it 😄

2022-06-30 15:45 UTC, alexeyr commented on lib/webpacker/helper.rb
> +      puts "To prevent duplicated stylesheet on the page, you should call stylesheet_pack_tag only once on the page. " \
Wait, won't you get the warning here even for the perfectly fine case of

> While this also generally applies to `stylesheet_pack_tag`, you may use multiple calls to stylesheet_pack_tag if, say, you require multiple <style> tags for different output media:

Am I missing something?

2022-06-30 16:11 UTC, pulkitkkr commented on lib/webpacker/helper.rb
> +      puts "To prevent duplicated stylesheet on the page, you should call stylesheet_pack_tag only once on the page. " \
As discussed over DM, removed the warning for now 😄

2022-06-30 17:04 UTC, merged

2022-06-30 20:25 UTC, justin808 commented on README.md
> +**Important** Similar to `append_javascript_pack_tag`, the `append_stylesheet_pack_tag` should be used anywhere in your application as long as it is executed BEFORE the `stylesheet_pack_tag`. However
Incorrect.

2022-06-30 20:25 UTC, justin808 commented on lib/webpacker/helper.rb
> +      "Please refer to https://github.com/shakacode/shakapacker/blob/master/README.md#usage for the usage guide"
Please refer to the documentation for stylesheet_pack_tag for more information.