For custom environments fall back to production defaults
shakacode/shakapacker pull request #168
Opened 2022-07-07 09:48 UTC by ur5us

Fixes #143

2022-07-08 08:05 UTC, tomdracz requested changes

2022-07-08 08:05 UTC, tomdracz commented on lib/webpacker/configuration.rb
> +        HashWithIndifferentAccess.new(config[env] || config["production"])
@ur5us think I'd actually prefer to use defaults key rather than production one, principle of least surprise. Need a quick spec for this too

2022-07-08 10:22 UTC, tomdracz commented on lib/webpacker/configuration.rb
> +        HashWithIndifferentAccess.new(config[env] || config["production"])
And a changelog entry 😆  @ur5us

2022-07-08 20:41 UTC, ur5us commented on lib/webpacker/configuration.rb
> +        HashWithIndifferentAccess.new(config[env] || config["production"])
@tomdracz While adding tests, I came along https://github.com/shakacode/shakapacker/blob/f5e6d97f83a713143ad7dd1f1ac1ba1fc7b7abdb/lib/webpacker/env.rb#L2 and https://github.com/shakacode/shakapacker/blob/f5e6d97f83a713143ad7dd1f1ac1ba1fc7b7abdb/lib/webpacker/env.rb#L24-L26 as my tests were failing. It looks like the default fallback is `production` when no environment is set. Should I deviate from that for this particular use case? Either way works for me, I just need to adapt the tests. I’m just not sure which fallback is least surprising.

2022-07-09 07:31 UTC, tomdracz commented on lib/webpacker/configuration.rb
> +        HashWithIndifferentAccess.new(config[env] || config["production"])
Good spot, I forgot about that one. Might be worth keeping production as a fallback after all. This would be consistent.

Need to trace how we populate env to the config though, if we already have fallback in env.rb, need to see why we're not providing that to the config in the first place 🤔

2022-07-09 07:46 UTC, tomdracz commented on lib/webpacker/configuration.rb
> +        HashWithIndifferentAccess.new(config[env] || config["production"])
Although... Looks like we are https://github.com/shakacode/shakapacker/blob/master/lib/webpacker/instance.rb#L18? 🤔

I'm now bit stumped as it seems the flow is already correct

- try to get current env
- if it's not defined in the webpacker.yml, we fallback to production
- we try to fetch value from user config (for the current env or production as a fallback)
- if it's not there, we fetch from gem defaults (again falling back to production but it should already merge other defaults)

So I think the fallback in the PR will be never reached. Am I missing something?

@manastyretskyi are you able to help out with the test case for the behaviour you were seeing? I think we need to try to cover that to know we're making the right changes

2022-07-09 07:53 UTC, tomdracz commented on lib/webpacker/configuration.rb
> +        HashWithIndifferentAccess.new(config[env] || config["production"])
Oh wait, I think I get it now.

If user config defines a new env and it's present in webpacker.yml, we'll never get the fallback. That means though the defaults will be fetched for non-existent key in defaults rather than fallback.

Sorry for being thick, it all makes sense now! And sorry for the lots of messages, but might help someone follow the thought process here.

@ur5us let's fallback on production then to keep it in line with behaviour elsewhere. Maybe just reference it by the constant in https://github.com/shakacode/shakapacker/blob/master/lib/webpacker/env.rb#L2 rather than new string so we've got one source of truth.

2022-07-09 07:58 UTC, ur5us commented on lib/webpacker/configuration.rb
> +        HashWithIndifferentAccess.new(config[env] || config["production"])
> If user config defines a new env and it's present in webpacker.yml, we'll never get the fallback. That means though the defaults will be fetched for non-existent key in defaults rather than fallback.

Yes, that’s the issue. I’m adding 2 tests for the various behaviors.

> Sorry for being thick, it all makes sense now! And sorry for the lots of messages, but might help someone follow the thought process here.

Works for me :smile:

2022-07-20 09:08 UTC, tomdracz reviewed
@ur5us Nice work, just one question/potential change and merge conflict, otherwise LGTM!

2022-07-20 09:08 UTC, tomdracz commented on lib/webpacker/env.rb
> -
@ur5us What's the reasoning for moving this from `Webpacker::Env` to main `Webpacker` class? I think it reads bit better under `Webpacker::Env` so would prefer to keep it that way unless there's a good reason for us moving this

2022-07-20 09:08 UTC, tomdracz commented on CHANGELOG.md
> +- fix default configurations not working for custom Rails environments [PR 168](https://github.com/shakacode/shakapacker/pull/168) by [ur5us](https://github.com/ur5us)
Will need to sort out merge conflict here ;)

2022-07-20 09:52 UTC, ur5us commented on lib/webpacker/env.rb
> -
@tomdracz I agree, it reads better under `Webpacker::Env`. The reason I moved it was due it now being a “shared” concern and to avoid requiring `Webpacker::Env`. `Webpacker::DEFAULT_ENV` would read better as an alternative.

2022-07-20 11:08 UTC, ur5us commented on lib/webpacker/env.rb
> -
…or maybe even `Webpacker::FALLBACK_ENV`.

2022-07-21 06:31 UTC, tomdracz commented on lib/webpacker/env.rb
> -
Makes sense. Shall we go with `Webpacker::DEFAULT_ENV` then? Reads nice and we solve the shared concern problem. Let's do that and  ship it @ur5us !

2022-07-21 08:49 UTC, ur5us commented on lib/webpacker/env.rb
> -
@tomdracz All done and rebased :tada:

2022-07-22 06:39 UTC, tomdracz approved these changes
Fantastic one @ur5us much appreciated 🎉

2022-07-22 06:39 UTC, tomdracz approved these changes

2022-07-22 06:39 UTC, merged