Enhanced process for managing gem resources
shakacode/shakapacker pull request #169
Opened 2022-07-07 16:03 UTC by RailsCod3rFuture

It was decided that gem resources should live in their own respective domain and we should remove the Gemfile.lock. So that AWS Inspector will not attempt to signal vulnerabilities exist -- that don't really.

2022-07-08 08:06 UTC, tomdracz requested changes
One thing missing - we should gitignore the Gemfile.lock and this should be good to go!

2022-07-09 07:56 UTC, tomdracz requested changes
One small change and it's good to go

2022-07-09 07:56 UTC, tomdracz commented on .gitignore
> +/Gemfile.lock
Just small tweak, let's lose the trailing slash so it's clear we're referencing file and not directory

2022-07-09 12:49 UTC, RailsCod3rFuture commented on .gitignore
> +/Gemfile.lock
made your suggestion.

2022-07-10 08:26 UTC, tomdracz approved these changes

2022-07-10 08:27 UTC, merged