Change NODE_ENV defaults
shakacode/shakapacker pull request #185
Opened 2022-09-05 14:19 UTC by mage1711

2022-09-06 13:26 UTC, alexeyr-ci1 commented on README.md
> +The setting of the NODE_ENV should be removed from the binstubs.
This should go to the changelog, not here.

2022-09-06 17:20 UTC, mage1711 commented on README.md
> +The setting of the NODE_ENV should be removed from the binstubs.
> This should go to the changelog, not here.

I added it to the changelog also https://github.com/shakacode/shakapacker/pull/185/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR10

and I think we should keep this line or move it somewhere else because the old binstubs will still have the old NODE_ENV defaults if a new install isn't done.

2022-09-07 01:34 UTC, justin808 requested changes

2022-09-07 01:34 UTC, justin808 commented on README.md
> +The setting of the NODE_ENV should be removed from the binstubs.
Please change, @mage1711: 
```
Older Shakapacker installations had the setting of a missing NODE_ENV in the binstubs as the default per RAILS_ENV is no longer set there.
```

2022-09-08 09:51 UTC, merged