Update Stylesheet Pack tag(s) to return Topological Order
shakacode/shakapacker pull request #193
Opened 2022-10-21 19:14 UTC by pulkitkkr

2022-10-21 21:57 UTC, justin808 commented
This looks really good. @tomdracz can you take a look?

2022-10-21 22:01 UTC, justin808 commented
Should we consider making this opt-in? Or maybe it's just more correct this way, so no need to give people one more option to consider?

I'll release a beta version for people to test.

2022-10-21 22:01 UTC, justin808 approved these changes

2022-10-21 22:16 UTC, justin808 requested changes

2022-10-21 22:16 UTC, justin808 commented on lib/rgl/topsort.rb
> +module RGL
This would conflict if the RGL gem were installed.

We should also comment on why we copied this.

2022-10-21 22:16 UTC, justin808 commented on CHANGELOG.md
> +- Update Stylesheet & Javascript Pack tag(s) to return packs in Topological Order by [pulkitkkr](https://github.com/shakacode/shakapacker/pull/185) in [PR 193](https://github.com/shakacode/shakapacke
Fixed what bug?

Maybe it's an Improvement?

This change ensures script and JS tags order all dependencies based on the order of all included entry points from the manifest. The old algorithm added dependencies by appending from the list and unique. The new way uses topological order.

##  Old way

```
a = A B C
d = D B C

for a, d
A B C D

for d, a
D B C A
```

## New way 
```
for a, d
A D B C

for d, a
D A B C
```

2022-10-24 14:39 UTC, kylemellander commented
I am wondering about copying over files from the RGL library in lieu of adding it as a dependency.  I understand the desire to reduce the number of dependencies, but this means that shakapacker is dependent on maintaining that code now, so things like security flaws etc. will be harder to track down and fix.

In addition, I'm no legal expert, but I wonder about these lines in the code and wonder if shakapacker needs to include their license file.

2022-10-27 14:28 UTC, tomdracz commented
Looks interesting BUT with a few caveats:
- I would definitely want this as non-default opt-in initially with a switch maybe in next major version
- As per @kylemellander I don't quite like how we pull stuff over from RGL rather than having it as dependency
- Is there an actual problem we're fixing here? If so, what is it. Can we have some specs that demonstrate us fixing this? The specs we've got in this PR feel to be bit vague to be fit for purpose IMO
- How does that affect all the other workarounds and jumping through the hoops by deduping loaded packs and setting up a queue to avoid double loading?

cc @pulkitkkr @justin808

2022-10-27 14:29 UTC, tomdracz commented on CHANGELOG.md
> +- Update Stylesheet & Javascript Pack tag(s) to return packs in Topological Order by [pulkitkkr](https://github.com/shakacode/shakapacker/pull/185) in [PR 193](https://github.com/shakacode/shakapacke
+1

2022-11-01 22:54 UTC, justin808 approved these changes
💯

2022-11-01 22:54 UTC, justin808 commented on CHANGELOG.md
> +- Update Stylesheet & Javascript Pack tag(s) to return packs in Topological Order by [pulkitkkr](https://github.com/shakacode/shakapacker/pull/185) in [PR 193](https://github.com/shakacode/shakapacke
@tomdracz is it worth noting any difference between the importance of order between JS and CSS assets? CSS seems more important because of precedence rules.

2022-11-01 22:54 UTC, justin808 commented
@pulkitkkr LGTM! please resolve conflict in the CHANGELOG and I'll merge and ship.

2022-11-26 04:41 UTC, justin808 commented
We're going to hold off on this one until we're sure we've fixing some bug.

2023-02-13 12:23 UTC, vaukalak commented
@pulkitkkr Could you please create or reference the issue on github you're trying to solve with this PR?

2023-06-06 21:19 UTC, ahangarha commented
@justin808 Should we include this in version 7?

2023-08-11 20:47 UTC, justin808 commented
We can revisit this one later if needed.

2023-08-11 20:47 UTC, closed without merging