Fix broken link
shakacode/shakapacker pull request #213
Opened 2022-11-22 22:32 UTC by itzbernoulli

Fix broken link to "Customizing Babel Config"

2022-11-23 06:59 UTC, ahangarha requested changes
If you experience a broken link anywhere else than GitHub, please share it here; otherwise I don't see any broken link here.

Please check the comment.

But I see a broken link at the very bottom of the this file. It is to the same page. There, we have extra `docs` in the link. I guess you wanted to fix that but introduced an new broken link. If so, please update your apply the required changes.

Thanks for your contribution.

2022-11-23 06:59 UTC, ahangarha commented on docs/v6_upgrade.md
> +1. Update `babel.config.js` if you need JSX support. See [Customizing Babel Config](./docs/customizing_babel_config.md)
Since this is a relative path and the target file is in the same directory as the original file, the current link works fine.

2022-11-23 11:00 UTC, itzbernoulli commented on docs/v6_upgrade.md
> +1. Update `babel.config.js` if you need JSX support. See [Customizing Babel Config](./docs/customizing_babel_config.md)
Thanks to noting that. In a bid to fix one I broke another but I have fixed the original broken link now.

2022-11-24 16:51 UTC, ahangarha approved these changes
Thanks for your contribution 🌺

2022-11-26 04:37 UTC, merged