WIP - Rewrite tests with RSpec
shakacode/shakapacker pull request #218
Opened 2022-12-01 10:48 UTC by ahangarha

All tests were rewritten in RSpec.

WIP:
- Squash commits
- Improve test titles
- Improve robustness of tests related to adding binstubs

2022-12-02 08:12 UTC, justin808 commented
@ahangarha many added files. Are some being deleted?

2022-12-02 21:14 UTC, ahangarha commented
Yes. Minitests should be deleted.

Since these files are mapping minitest files, we can modify commits in a way that we dont delete old files and create new ones. Is this more desirable?

2022-12-03 12:11 UTC, tagliala commented
Hi,

Just out of curiosity, can I ask the main reasons behind this  change?

2022-12-05 05:03 UTC, justin808 commented
We'll make the tests more similar to the test suite of https://github.com/shakacode/react_on_rails.

2022-12-05 05:04 UTC, justin808 commented
> Yes. Minitests should be deleted.

@ahangarha you can delete the old ones if you're sure that they're all covered.

2022-12-15 16:16 UTC, ahangarha commented
> > Yes. Minitests should be deleted.
> 
> @ahangarha you can delete the old ones if you're sure that they're all covered.

@justin808 
All the test cases (268) are rewritten in RSpec and Minitests are removed. Not only they are covered, but some minor bugs in two of them are also addressed. As long as there is no issue with the implementation of the two mentioned files in the PR description, all is good.

I have just noticed that `rake test` doesn't work. The default task to run with `rake` is set to be `spec` which runs RSpec. I think this is the last piece to be addressed for this PR.

2022-12-23 20:58 UTC, justin808 requested changes

2022-12-23 20:58 UTC, justin808 commented on Rakefile
> +  RSpec::Core::RakeTask.new(:test)
should we match https://relishapp.com/rspec/rspec-core/docs/command-line/rake-task

2022-12-23 20:58 UTC, justin808 commented on spec/dev_server_runner_spec.rb
> +    end
Above should use mocks from rspec.

2022-12-26 10:13 UTC, ahangarha commented on spec/dev_server_runner_spec.rb
> +    end
Done ✅

2023-01-09 13:18 UTC, ahangarha commented on Rakefile
> +  RSpec::Core::RakeTask.new(:test)
@Judahmeek Do you have any thoughts here?

2023-01-09 14:09 UTC, vaukalak commented on Rakefile
> +  RSpec::Core::RakeTask.new(:test)
@ahangarha please make sure you change this line https://github.com/shakacode/shakapacker/blob/master/.github/workflows/ruby.yml#L43

2023-01-09 14:22 UTC, vaukalak commented on spec/helper_spec.rb
> +    before :example do
@ahangarha if this need to run before each test, let call that `before (:each)`.

2023-01-09 14:39 UTC, ahangarha commented on Rakefile
> +  RSpec::Core::RakeTask.new(:test)
Sure.
If the conclusion is to use `:spec` instead of `:test`, I will take care of CI and documentation.

2023-01-09 14:40 UTC, ahangarha commented on Rakefile
> +  RSpec::Core::RakeTask.new(:test)
@justin808 
I read your comment as a question and that is why this change is not done yet. I am waiting for a conclusion otherwise making the change is a matter of a couple of minutes.

2023-01-09 14:54 UTC, ahangarha commented on spec/helper_spec.rb
> +    before :example do
Done

2023-01-09 19:42 UTC, Judahmeek commented on Rakefile
> +  RSpec::Core::RakeTask.new(:test)
@justin808 I don't think so.

I told @ahangarha that I preferred `:test` over `:spec` because `:test` is a verb & thus more grammatically correct.

2023-01-09 19:44 UTC, Judahmeek approved these changes

2023-01-09 20:42 UTC, justin808 approved these changes

2023-01-10 08:04 UTC, merged