Update upgrade documentation
shakacode/shakapacker pull request #222
Opened 2022-12-08 05:22 UTC by Judahmeek

I don't understand why we're mentioning `shakapacker` in the instructions to upgrade from Webpacker v5 to Webpacker v6 RC.

2022-12-08 22:49 UTC, mage1711 requested changes

2022-12-08 22:49 UTC, mage1711 commented on docs/v6_upgrade.md
> +   yarn add webpacker@6.0.0-rc.6 --exact
This line should be changed to `yarn add @rails/webpacker@6.0.0-rc.6 --exact`

2022-12-09 10:44 UTC, mage1711 commented on docs/v6_upgrade.md
> -1. **Ensure no nested directories in your `source_entry_path`.** Check if you had any entry point files in child directories of your `source_entry_path`. Files for entry points in child directories a
why was this removed instead of changing it to 
`Files for entry points in child directories are not supported by webpacker v6` because the same instructions apply to webpacker v6

2022-12-10 18:26 UTC, Judahmeek commented on docs/v6_upgrade.md
> -1. **Ensure no nested directories in your `source_entry_path`.** Check if you had any entry point files in child directories of your `source_entry_path`. Files for entry points in child directories a
@mage1711 because these instructions were also stated on [line 53](https://github.com/shakacode/shakapacker/pull/222/files#diff-aa580ff25f7f9251e77d3c2418cc34dde4f44ddca29c6e6db12752fdde42710eR53)

2022-12-11 21:24 UTC, mage1711 approved these changes

2022-12-11 23:02 UTC, justin808 commented on docs/v6_upgrade.md
> +   The v6 configuration does not allow nesting, so as to allow placing the entry points at in the root directory of JavaScript. You can find this change [here](https://github.com/rails/webpacker/comm
@Judahmeek 
Why this change?

There's a new setting to allow nesting that should become the default.

2022-12-11 23:02 UTC, justin808 commented on docs/v6_upgrade.md
> +   gem 'webpacker', '6.0.0.rc.6'
I see, this is really confusing about having the intermediate steps here...

2022-12-15 16:37 UTC, Judahmeek commented on docs/v6_upgrade.md
> +   The v6 configuration does not allow nesting, so as to allow placing the entry points at in the root directory of JavaScript. You can find this change [here](https://github.com/rails/webpacker/comm
@justin808 because this is the instructions for upgrading to Webpacker v6 RC

2022-12-23 21:59 UTC, justin808 requested changes

2022-12-23 21:59 UTC, justin808 commented on docs/v6_upgrade.md
> +   The v6 configuration does not allow nesting, so as to allow placing the entry points at in the root directory of JavaScript. You can find this change [here](https://github.com/rails/webpacker/comm
```
The v6 RC configuration does not allow nesting. The newer version of v6 does. So you should not convert your code to non-nesting if you can change the setting to allowing nesting.
```

2022-12-23 22:02 UTC, merged