Fix bin/setup modification failure in installation
shakacode/shakapacker pull request #229
Opened 2022-12-26 14:31 UTC by ahangarha

Due to different content of `bin/setup` in different Rails versions, the earlier version of the generator couldn't modify this file properly in all circumstances.

This commit handles the following scenarios:
- If there is a commented line for `system('bin/yarn')`, uncomment it.
- Otherwise, regardless of using single or double quotations in different Rails versions, add `system! 'bin/yarn'` after the intended line.

closes #226

2022-12-29 00:23 UTC, Judahmeek requested changes

2022-12-29 00:23 UTC, Judahmeek commented on lib/install/template.rb
> +    gsub_file setup_path, "# system('bin/yarn')", 'system! "bin/yarn"'
@justin808 prefers that we use parentheses `()` whenever possible with ruby methods

Example: `gsub_file(setup_path, "# system('bin/yarn')", 'system! "bin/yarn"')`

2022-12-29 00:23 UTC, Judahmeek commented on lib/install/template.rb
> +      insert_into_file setup_path.to_s, <<-RUBY, after: pattern
please add parentheses

2023-01-03 09:20 UTC, ahangarha commented on lib/install/template.rb
> +    gsub_file setup_path, "# system('bin/yarn')", 'system! "bin/yarn"'
Thanks for mentioning this. I also prefer to add parentheses. In some cases, I just try to follow the surrounding code convention.

If using parentheses is what we all prefer, then it is good. Will do this now onward.

2023-01-03 09:33 UTC, ahangarha commented on lib/install/template.rb
> +    gsub_file setup_path, "# system('bin/yarn')", 'system! "bin/yarn"'
@Judahmeek 
Should I add parentheses to all other methods in the file (in order to keep consistency)? If not, do we have any rule on where to add parentheses and where to not (given that functionally there be no difference)?

2023-01-09 10:04 UTC, ahangarha commented on lib/install/template.rb
> +      insert_into_file setup_path.to_s, <<-RUBY, after: pattern
@Judahmeek Done but only on the code I added.

2023-01-09 10:08 UTC, ahangarha commented on lib/install/template.rb
> +  end
@Judahmeek @justin808 
What about adding these lines at the end of the file if we couldn't find the pattern? The job of this step in the generator is to ensure we have `system!("bin/yarn")` in the `setup` file. So why should we ask the user to do it manually?

I think it would be good to print out some text and say thought we have updated the `setup` file, but the format of the file was not what we expected. This way, we can ask the developer to review the content of this file and ensure everything is right in the file.

It is not a very important thing to be worried about but I think if we are updating this part, we do it in the right way. Is my proposal the right way? What do you think?

2023-01-16 23:37 UTC, justin808 commented
@ahangarha I'll merge after you update the CHANGELOG.

However, I'm not convinced this modification regarding bin/yarn is even needed longer term.

2023-01-19 12:38 UTC, ahangarha commented
> @ahangarha I'll merge after you update the CHANGELOG.
> 
> However, I'm not convinced this modification regarding bin/yarn is even needed longer term.

@justin808 I updated the changelog.
If we don't need such modification at all, then we should remove it entirely.
I think it would be good to make a final decision about this matter before our next major release.

2023-01-30 14:31 UTC, vaukalak commented on lib/install/template.rb
> +  if File.read(setup_path).match? Regexp.escape("  # system('bin/yarn')\n")
@ahangarha 

[] please extract `system('bin/yarn')` to a const, also why it's `system('bin/yarn')` and `system**!**('bin/yarn')` in other places?
[] please add a warn, that the file has been modified.
[] (optional), add a comment what and why we are uncommenting, unless this will not be intuitive from the log above.

2023-01-30 14:33 UTC, vaukalak commented on lib/install/template.rb
> +        It seems your `bin/setup` file doesn't have the expected content.
Do we have a section in the docs, which might be referenced in this warn message?

2023-01-30 14:35 UTC, vaukalak requested changes
please give feedback to the comments above.

2023-01-30 15:18 UTC, ahangarha commented on lib/install/template.rb
> +  if File.read(setup_path).match? Regexp.escape("  # system('bin/yarn')\n")
- May you elaborate on the extraction of `system('bin/yarn')`? If it is for DRY, I don't think this is a good place to do so because of having a different format in some parts. And then if I extract it, I think we get into a readability issue.
- Regarding `system` and `system!`, rails 5 used `system` only. I didn't check if it was intended. Since we use `!` for it, it is uncommented and changed to `system!`. Do you think there was a particular reason behind using `system` in Rails 5?
- Do we need to warn the user about this? I think the message generated by `gsub_file` and `insert_into_file` is sufficient and enough informative.
- Well, as per my understanding we want to run `yarn install` when we run `./bin/setup` script. In rails 5 and 6, they had this item in the file. In Rails 5 it was commented and without `!` and in Rails 6 it was uncommented with `!`. In Rails 7 they removed it entirely (even if one specifies `--javascript=webpack`).

2023-01-30 15:23 UTC, ahangarha commented on lib/install/template.rb
> +        It seems your `bin/setup` file doesn't have the expected content.
I don't think so. But also see my comment [here](https://github.com/shakacode/shakapacker/pull/229#discussion_r1064466091):

> What about adding these lines at the end of the file if we couldn't find the pattern? The job of this step in the generator is to ensure we have `system!("bin/yarn")` in the `setup` file. So why should we ask the user to do it manually?

I didn't get any response on it. Do you have any?

2023-01-30 16:43 UTC, vaukalak commented on lib/install/template.rb
> +  if File.read(setup_path).match? Regexp.escape("  # system('bin/yarn')\n")
```
Regarding system and system!, rails 5 used system only. I didn't check if it was intended. Since we use ! for it, it is uncommented and changed to system!. Do you think there was a particular reason behind using system in Rails 5?
```
@ahangarha thanks, this makes sense. Could you please then just some comments, or extract a function, so the code will be easier to understand?

2023-01-30 16:50 UTC, vaukalak commented on lib/install/template.rb
> +        It seems your `bin/setup` file doesn't have the expected content.
@ahangarha I think it's a good idea to add both in this case and keep the message, which will give heads-up to the user.

2023-01-31 11:41 UTC, vaukalak approved these changes

2023-01-31 20:46 UTC, merged