Add prepend_javascript_pack_tag helper
shakacode/shakapacker pull request #235
Opened 2023-01-11 11:43 UTC by paypro-leon

In our codebase we had a similar approach for Webpacker 5 for `append_javascript_pack_tag` helper, but we used `unshift` instead of appending to the array.

Using `append_javascript_pack_tag` causes issues for us where we expect some entries to go before the appended entries added by the main view or partials.

Adding `prepend_javascript_pack_tag` to allow a pack to go to the beginning of the entry array would give us more flexibility in the order of the entries inserted by `javascript_pack_tag`.

2023-01-16 10:10 UTC, ahangarha approved these changes
Thanks for your contribution.
And thanks for updating the changelog and adding specs for these changes.

2023-01-16 13:12 UTC, paypro-leon commented
@ahangarha No problem, and thank you guys for continuing and improving `webpacker`!

2023-01-16 23:31 UTC, justin808 requested changes
Looking great! I'd like to ship this ASAP.

We're mainly missing the documentation. Please check for the docs for `append_javascript_pack_tag` and update accordingly.

2023-01-16 23:31 UTC, justin808 commented on lib/webpacker/helper.rb
> +      yield defer ? :deferred : :non_deferred
I prefer adding the argument with parens.

```rb
yield(defer ? :deferred : :non_deferred)
```

2023-01-16 23:31 UTC, justin808 commented on lib/webpacker/helper.rb
> +      javascript_pack_tag_queue[hash_key].unshift *names
Use parens for argument.

2023-01-18 11:20 UTC, paypro-leon commented
@justin808 Wasn't sure if we should split up the `append_javascript_pack_tag` and `prepend_javascript_pack_tag` documentation in the README. For now I kept them together.

2023-01-25 19:00 UTC, vaukalak approved these changes

2023-01-31 20:56 UTC, merged

2023-01-31 20:56 UTC, justin808 commented
Big thanks @paypro-leon!