fixed babel configuration for #208
shakacode/shakapacker pull request #240
Opened 2023-01-25 15:39 UTC by vaukalak

In specific scenarios, you would need to transpile some of `node_modules`. This addition allows to specify `node_modules` to include via `webpacker.yml => additional_paths` configuration.

closes #208

2023-01-26 08:10 UTC, justin808 requested changes
1. Create a new setting, like `packages_to_transpile`
2. Don't overload `additional_paths` 
3. Needs documentation and changelog

2023-01-26 08:10 UTC, justin808 commented on package/rules/__tests__/__utils__/webpack.js
> +}
editor setup is incorrect

needs new line

2023-01-26 08:10 UTC, justin808 commented on package/rules/__tests__/babel.js
> +    test('process included node_modules', async () => {
we should never transpile all of node_modules. Are you checking for only the additional paths?

2023-01-26 08:10 UTC, justin808 commented on package/rules/__tests__/babel.js
> +        expect(tracked[included]).toBeTruthy();
Need to check that that the files outside of node_modules/included and inside of node_modules are not transpiled, in at least one test.

2023-01-26 08:10 UTC, justin808 commented on package/rules/esbuild.js
> -  include: [sourcePath, ...additionalPaths].map((p) => {
Nice to dry this up! 👏

2023-01-26 15:50 UTC, vaukalak commented on package/rules/__tests__/babel.js
> +        expect(tracked[included]).toBeTruthy();
@justin808 we do have such test: https://github.com/shakacode/shakapacker/pull/240/files/d5b2d1744eaf17915aa36dd842e3d27ca414b317#diff-45330288787adaa7643887ecb63f58775bebe604da29c9789f0d5444a12a4ce7R44

2023-01-26 15:53 UTC, vaukalak commented on package/rules/__tests__/babel.js
> +    test('process included node_modules', async () => {
@justin808 sure we do, and also we do have a test case for this. I'll work on a better verbiage.

2023-01-26 16:19 UTC, vaukalak commented on package/rules/__tests__/__utils__/webpack.js
> +}
@justin808 thanks fixed, and created a new issue: https://github.com/shakacode/shakapacker/issues/242

2023-01-30 15:49 UTC, vaukalak commented
> 1. Create a new setting, like `packages_to_transpile`
> 2. Don't overload `additional_paths`
> 3. Needs documentation and changelog

@justin808 I've updated the changelog, but I'm not sure how adding additional property `packages_to_transpile` would be helpful. The code of webpack rules wouldn't change from what we have in this PR. We do override `additional_paths` only during tests. The only real difference would be in the configuration:

```yml
additional_paths: ['app/assets', 'node_modules/to_transpile']
```
vs
```yml
additional_paths: ['app/assets']
packages_to_transpile: ['node_modules/to_transpile']
```

So `packages_to_transpile` would become the same thing as `additional_paths`, however with `node_modules` support. Those properties will be merged anyway when creating the configuration for webpack.  So, I don't know how it can be helpful, IMHO it will only add more confusion.

2023-02-10 08:40 UTC, justin808 commented
Let's update the branch and merge it.

2023-02-12 00:40 UTC, merged