Rename Webpacker instances to shakapacker
shakacode/shakapacker pull request #245
Opened 2023-02-06 13:37 UTC by ahangarha

2023-02-13 12:31 UTC, vaukalak commented on lib/shakapacker/base_strategy.rb
> +module Shakapacker
@ahangarha I'm not sure if that's possible, but if this is just a copy of existent  `webpacker/` files, could we use `git-move`, to make sure we preserve the history?

2023-02-13 12:31 UTC, vaukalak commented on lib/shakapacker/base_strategy.rb
> +module Shakapacker
I mean hear and other files.

2023-02-13 12:36 UTC, vaukalak commented on lib/tasks/webpacker/check_node.rake
> +  desc "[DEPRECATED] Verifies if Node.js is installed"
`[DEPRECATED] (user shakapacker...) Verifies if Node.js is installed`

2023-02-13 12:36 UTC, vaukalak commented on lib/tasks/webpacker/info.rake
> +  desc "[DEPRECATED] Provide information on Shakapacker's environment"
I would add `[DEPRECATED] (user shakapacker...) Verifies if Node.js is installed` to all of this commands.

2023-02-13 15:09 UTC, ahangarha commented on lib/shakapacker/base_strategy.rb
> +module Shakapacker
I am not sure why but some files have proper history and some don't. For example [./lib/shakapacker/webpack_runner.rb](https://github.com/shakacode/shakapacker/blame/webpacker-to-shakapacker/lib/shakapacker/webpack_runner.rb) has proper commit history.

Any idea how to fix this?

2023-02-13 15:11 UTC, ahangarha commented on lib/tasks/webpacker/check_node.rake
> +  desc "[DEPRECATED] Verifies if Node.js is installed"
Initially, I was adding more information in all places. Then I thought maybe this is not necessary. I think as we go forward, we get better sense on where and how to show deprecatio warning.

2023-02-13 15:16 UTC, ahangarha commented on lib/shakapacker/base_strategy.rb
> +module Shakapacker
But see! Even this file (base_strategy) has history: https://github.com/shakacode/shakapacker/commits/45c67fca213f0ccb7ca108d06bdcb161d247c22b/lib/webpacker/base_strategy.rb?browsing_rename_history=true&new_path=lib/shakapacker/base_strategy.rb&original_branch=webpacker-to-shakapacker

2023-02-14 07:41 UTC, justin808 requested changes
https://www.rubyguides.com/2018/10/delegate-methods-in-ruby/

PR should be much smaller.

2023-02-14 07:41 UTC, justin808 commented on lib/shakapacker.rb
> +require "active_support/core_ext/module/attribute_accessors"
https://git-scm.com/docs/git-mv

2023-02-14 07:41 UTC, justin808 commented on lib/tasks/shakapacker.rake
> +  "shakapacker:clean"                   => "Remove old compiled webpacks",
old compiled bundles

2023-02-14 07:41 UTC, justin808 commented on lib/tasks/webpacker/clean.rake
> +    Rake::Task["#{prefix}shakapacker:clean"].invoke(args.keep, args.age)
alert deprecated before you call this

2023-02-14 07:41 UTC, justin808 commented on lib/tasks/webpacker/clean.rake
> +    Rake::Task["#{prefix}shakapacker:clean"].invoke(args.keep, args.age)
We can have another PR that adds back the deprecated rakes.

2023-02-14 07:41 UTC, justin808 commented on lib/webpacker/dev_server_runner.rb
>          env = Webpacker::Compiler.env
Why not Shakapacker::Compiler.env?

2023-02-14 07:41 UTC, justin808 commented on lib/webpacker/helper.rb
>      Webpacker.instance
shakapacker.instance?

2023-02-14 14:40 UTC, ahangarha commented on lib/shakapacker.rb
> +require "active_support/core_ext/module/attribute_accessors"
I did almsot the same thing in [this commit](https://github.com/shakacode/shakapacker/commit/45c67fca213f0ccb7ca108d06bdcb161d247c22b) but no effect.

There are two exceptions: one is this file (I could do better) and `railtie.rb` (where I don't know why it didn't consider it as a move). Rest should be fine but it is not.

2023-02-14 14:44 UTC, ahangarha commented on lib/webpacker/dev_server_runner.rb
>          env = Webpacker::Compiler.env
Just for having consistence in the code base. Still, `Webpacker::Comiler` inherits entirely from `Shakapacker::Compiler`: https://github.com/shakacode/shakapacker/blob/d3d84a02c9c565f89a74f9b5e30d1446c6d0b745/lib/webpacker/compiler.rb#L1

2023-02-18 16:07 UTC, ahangarha commented on lib/shakapacker/base_strategy.rb
> +module Shakapacker
This comment is now outdated

2023-02-18 16:07 UTC, ahangarha commented on lib/tasks/webpacker/info.rake
> +  desc "[DEPRECATED] Provide information on Shakapacker's environment"
This comment is now outdated

2023-02-18 16:08 UTC, ahangarha commented on lib/webpacker/helper.rb
>      Webpacker.instance
This comment is now outdated

2023-02-18 16:08 UTC, ahangarha commented on lib/webpacker/dev_server_runner.rb
>          env = Webpacker::Compiler.env
This comment is now outdated

2023-02-18 16:08 UTC, ahangarha commented on lib/tasks/webpacker/clean.rake
> +    Rake::Task["#{prefix}shakapacker:clean"].invoke(args.keep, args.age)
This comment is now outdated

2023-02-18 16:08 UTC, ahangarha commented on lib/tasks/webpacker/check_node.rake
> +  desc "[DEPRECATED] Verifies if Node.js is installed"
This comment is now outdated

2023-02-18 16:50 UTC, ahangarha commented on lib/tasks/shakapacker.rake
> +  "shakapacker:clean"                   => "Remove old compiled webpacks",
Applied

2023-02-24 07:43 UTC, vaukalak commented on package/rules/__tests__/swc.js
> +    console.log('ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ')
@ahangarha is this change expected?

2023-02-24 07:50 UTC, vaukalak commented
Otherwise LGTM

2023-03-10 21:28 UTC, justin808 requested changes
Make a branch called

webpacker-v6.7

**otherwise this PR will then reflect all the changes on the other branch**

and change base of this PR to that branch.

merge after fixes

then change other PR to be off of this new branch

then merge

then I'll push pre-release on the branch

2023-03-10 21:28 UTC, justin808 commented on CHANGELOG.md
> +- Rename Webpacker to Shakapacker in entire project including config files, binstubs, environment variables,... [PR157](https://github.com/shakacode/shakapacker/pull/157) by [ahangarha](https://githu
But 6.x is not a breaking change.

2023-03-10 21:28 UTC, justin808 commented on README.md
> +You will need your file system to correspond to the setup of your `shakapacker.yml` file.
```
You will need your file system to correspond to the setup of your `config/shakapacker.yml` file.
```

2023-03-10 21:28 UTC, justin808 commented on README.md
> +These view helpers take your `shakapacker.yml` configuration file, along with the resulting webpack compilation `manifest.json` and generate the HTML to load the assets.
```
These view helpers take your `shakapacker.yml` configuration file and the resulting webpack compilation `manifest.json` and generate the HTML to load the assets.
```

2023-03-10 21:28 UTC, justin808 commented on README.md
> +We encourage you to contribute to Shakapacker/Shakapacker! See [CONTRIBUTING](CONTRIBUTING.md) for guidelines about how to proceed. We have a [Slack discussion channel](https://reactrails.slack.com/j
```
We encourage you to contribute to Shakapacker! See [CONTRIBUTING](CONTRIBUTING.md) for guidelines about how to proceed. We have a [Slack discussion channel](https://reactrails.slack.com/join/shared_invite/enQtNjY3NTczMjczNzYxLTlmYjdiZmY3MTVlMzU2YWE0OWM0MzNiZDI0MzdkZGFiZTFkYTFkOGVjODBmOWEyYWQ3MzA2NGE1YWJjNmVlMGE).
```

2023-03-11 10:11 UTC, ahangarha commented on CHANGELOG.md
> +- Rename Webpacker to Shakapacker in entire project including config files, binstubs, environment variables,... [PR157](https://github.com/shakacode/shakapacker/pull/157) by [ahangarha](https://githu
This PR is breaking. The other PR makes these changes non-breaking.

Some background:
We were going to make a breaking release (v7) out of this branch. Later we decided to add backward compatibility for perhaps the last v6.x.

2023-03-11 10:15 UTC, ahangarha commented on package/rules/__tests__/swc.js
> +    console.log('ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ')
Fixed

2023-03-11 10:15 UTC, ahangarha commented on CHANGELOG.md
> +- Rename Webpacker to Shakapacker in entire project including config files, binstubs, environment variables,... [PR157](https://github.com/shakacode/shakapacker/pull/157) by [ahangarha](https://githu
Done

2023-03-13 08:59 UTC, justin808 approved these changes

2023-03-13 09:00 UTC, merged