WIP - add backward compatibility
shakacode/shakapacker pull request #252
Opened 2023-02-18 16:51 UTC by ahangarha

2023-02-24 07:49 UTC, vaukalak commented on lib/shakapacker/configuration.rb
> +    webpacker_key = key.to_s.gsub("shakapacker", "webpacker").to_sym
not sure, but maybe we could add a warning here?

2023-02-24 07:50 UTC, vaukalak commented
Otherwise LGTM

2023-02-24 21:51 UTC, justin808 requested changes

2023-02-24 21:51 UTC, justin808 commented on .github/workflows/ruby-backward-compatibility.yml
> +        ruby: ['2.6', '2.7', '3.0']
3.1?

2023-02-24 21:51 UTC, justin808 commented on lib/shakapacker/configuration.rb
> +    shakapacker_precompile?
we can add a deprecation message here

2023-02-24 21:51 UTC, justin808 commented on lib/shakapacker/configuration.rb
> +    webpacker_key = key.to_s.gsub("shakapacker", "webpacker").to_sym
and there are no other keys with webpacker here: https://github.com/shakacode/shakapacker/blob/master/lib/install/config/webpacker.yml

so extra logic is unnecessary

2023-02-24 21:51 UTC, justin808 commented on lib/shakapacker/configuration.rb
> +    webpacker_key = key.to_s.gsub("shakapacker", "webpacker").to_sym
```rb
puts "some deprecation warning"
return data.fetch(:webpacker_precompile)
```

instead of 
```rb
webpacker_key = key.to_s.gsub("shakapacker", "webpacker").to_sym
data.fetch(webpacker_key, defaults[key])
```

2023-02-24 21:51 UTC, justin808 commented on lib/shakapacker/deprecation_helper.rb
> +          Using `config/webpacker.yml` is deprecated. Consider using `config/shakapacker.yml`.
Using `config/webpacker.yml` is deprecated. Change the name to  `config/shakapacker.yml` and see XXX for other changes.

2023-02-24 21:51 UTC, justin808 commented on lib/shakapacker/deprecation_helper.rb
> +      ENV[shakapacker_key] = ENV[webpacker_key]
Nice work.

2023-02-24 21:51 UTC, justin808 commented on lib/shakapacker/deprecation_helper.rb
> +        \e[33m
We should see if the Rails core code uses colors for warnings and deprecations.

DataDog logging discourages this.

2023-02-24 21:51 UTC, justin808 commented on lib/shakapacker/deprecation_helper.rb
> +        \e[0m
we can abstract the color wrapper

2023-02-24 21:51 UTC, justin808 commented on lib/shakapacker/instance.rb
> +    @config_path = config_path
why change? rubocop?

2023-02-24 21:51 UTC, justin808 commented on lib/shakapacker/instance.rb
> +    @config_path = Shakapacker::get_config_file_path_with_backward_compatibility(@config_path)
```rb
    @root_path = root_path
    # For backward compatibility
    @config_path = Shakapacker::get_config_file_path_with_backward_compatibility(config_path)
``

2023-02-24 21:51 UTC, justin808 commented on lib/tasks/shakapacker/check_binstubs.rake
> +         - Ensure the `bin` directory and `bin/shakapacker` are not included in .gitignore.
consider link to current version: https://github.com/shakacode/shakapacker/blob/master/lib/install/bin/webpacker

2023-02-24 21:51 UTC, justin808 commented on package/utils/helpers.js
> +      process.env[shakapackerKey] = webpackerEnvvalue
webpackerEnvvalue ==> webpackerEnvValue

2023-02-24 21:51 UTC, justin808 commented on package/utils/helpers.js
> +  webpackerEnvVariables.forEach(([webpackerEnvKey, webpackerEnvvalue]) => {
webpackerEnvvalue ==> webpackerEnvValue

2023-02-24 21:51 UTC, justin808 commented on package/utils/helpers.js
> +      process.env[shakapackerKey] = webpackerEnvvalue
are you 100% sure this works?

2023-02-24 21:51 UTC, justin808 commented on package/utils/helpers.js
> +}
```js
const fs = require('fs');
const path = './my-awesome-file.txt';

if (fs.existsSync(path)) {
  console.log('file exists');
} else {
  console.log('file not found!');
}
```

2023-02-24 21:51 UTC, justin808 commented on package/utils/helpers.js
> +}
then inline your implementation

2023-02-24 21:51 UTC, justin808 commented on package/utils/helpers.js
> +  fileExists,
fileExists is probably not necessary

2023-02-24 21:51 UTC, justin808 commented on spec/backward_compatibility_specs/webpacker_test_app/.gitignore
> +log/
see red

2023-02-24 21:51 UTC, justin808 commented on spec/backward_compatibility_specs/webpacker_test_app/.gitignore
> +log/
missed new line

2023-02-24 21:51 UTC, justin808 commented on spec/spec_helper_initializer.rb
> +require_relative "test_app/config/environment"
name needs to be more descriptive, maybe with some comments at the beginning of this file


why is this code separate from spec_helper.rb?

2023-02-24 21:51 UTC, justin808 commented on spec/spec_helper_initializer.rb
> +require_relative "test_app/config/environment"
Could we run this code with a before_each? this file got required in many different files.

2023-02-28 10:23 UTC, ahangarha commented on .github/workflows/ruby-backward-compatibility.yml
> +        ruby: ['2.6', '2.7', '3.0']
If you are okay with updating our test environment in this PR, I can do it. But also we can do it in a separate PR.

My proposal:
Ruby:
```diff
- ruby: ['2.6', '2.7', '3.0']
+ ruby: ['2.7', '3.1', '3.2']
```

Node:
```diff
- node: [12.x, 14.x, 16.x]
+ node: [14.x, 16.x, 18.x]
```

2023-02-28 10:29 UTC, ahangarha commented on lib/shakapacker/deprecation_helper.rb
> +          Using `config/webpacker.yml` is deprecated. Consider using `config/shakapacker.yml`.
What about a homogenous message in this format:
```
DEPRECATION NOTICE:

Consider using `NEW` instead of the deprecated `OLD`.
Read more: https://github.com/shakacode/shakapacker/docs/v7_upgrade.md
```

2023-02-28 10:39 UTC, ahangarha commented on package/utils/helpers.js
> +}
Applied

2023-02-28 10:47 UTC, ahangarha commented on spec/spec_helper_initializer.rb
> +require_relative "test_app/config/environment"
I am afraid we can do this unless we want to initialize a new `Rails.application` for each single test case, which is expensive.

This would be a temporary implementation till Version 7. From version 7 and dropping backward compatibility, we go back to what we used to be.

I agree about the filename. The file initializes a Rails application and sets Shakapacker or Webpacker configuration. Maybe `app_initializer` would be a better name. I am afraid if I give it such a name and leave the file in the same directory as other spec files, we cannot recognize it easily. Maybe put it in a `helper` directory? Not sure of the best approach.

2023-02-28 14:18 UTC, ahangarha commented on package/utils/helpers.js
> +  fileExists,
Done

2023-02-28 15:30 UTC, ahangarha commented on package/utils/helpers.js
> +  webpackerEnvVariables.forEach(([webpackerEnvKey, webpackerEnvvalue]) => {
Done

2023-02-28 15:31 UTC, ahangarha commented on spec/backward_compatibility_specs/webpacker_test_app/.gitignore
> +log/
done

2023-02-28 15:49 UTC, ahangarha commented on lib/shakapacker/configuration.rb
> +    shakapacker_precompile?
done

2023-03-08 04:19 UTC, justin808 commented
Ready?

2023-03-10 21:13 UTC, justin808 requested changes

2023-03-10 21:13 UTC, justin808 commented on docs/v7_upgrade.md
> +Shakapacker v6 used a fork of the Webpacker module internally. As a result, in many cases including config filename, environment variables, rake tasks,... we were using Webpacker name. Starting from
```
## Usages of "webpacker" should now be "shakapacker"

Shakapacker v6 kept the 'webpacker' spelling. As a result, many config filenames, environment variables, rake tasks, etc., used the 'webpacker' spelling. Shakapacker 7 requires renaming to the 'shakapacker' spelling.

2023-03-10 21:13 UTC, justin808 commented on docs/v7_upgrade.md
> +### Upgrade to 6.6.x
6.x ?

2023-03-10 21:13 UTC, justin808 commented on docs/v7_upgrade.md
> +Before upgrading to version 7 (future major release), make sure you upgrade your Shakapacker to the latest 6.6.x version. With the help of backward compatibility, you should have no issue running you
6.x

2023-03-10 21:13 UTC, justin808 commented on docs/v7_upgrade.md
> +Before upgrading to version 7 (future major release), make sure you upgrade your Shakapacker to the latest 6.6.x version. With the help of backward compatibility, you should have no issue running you
Before upgrading to version 7, upgrade Shakapacker to the latest 6.6.x version. You should have no issue running your application. However, you will see many deprecation messages. Once you've updated your app to clear the deprecation messages, then you should update to v7.

2023-03-10 21:13 UTC, justin808 commented on docs/v7_upgrade.md
> +- Consider requiring and using `Shakapacker` module instead of `Webpacker`.
```
#### Ruby Usage
- Rename constant `Webpacker` to  `Shakapacker`.
- Rename`Shakapacker.config.webpacker_precompile?` method, replace it with `Shakapacker.config.shakapacker_precompile?`
```

2023-03-10 21:13 UTC, justin808 commented on docs/v7_upgrade.md
> +#### Config file
```
#### `webpacker.yml` renamed and updated

2023-03-10 21:13 UTC, justin808 commented on docs/v7_upgrade.md
> +- If you use `Shakapacker.config.webpacker_precompile?` method, replace it with `Shakapacker.config.shakapacker_precompile?`
remove this, it's not part of the config file.

Put under Ruby Changes above.

2023-03-10 21:13 UTC, justin808 commented on docs/v7_upgrade.md
> +- `bin/webpacker` and `bin/webpacker-dev-server` are renamed to `bin/shakapacker` and `bin/shakapacker-dev-server`. Since there are internal changes as well, the best way is to run `rake shakapacker:
```
- Rename `bin/webpacker` and `bin/webpacker-dev-server`  `bin/shakapacker` and `bin/shakapacker-dev-server` and update the content of these files to change 'webpacker' to 'shakapacker'.
- Alternatively,  run `rake shakapacker:binstubs` to get the new files in place. and delete the old webpacker ones.
```

2023-03-10 21:13 UTC, justin808 commented on docs/v7_upgrade.md
> +- All the environment variables in the format of `WEBPACKER_XYZ` should be renamed to `SHAKAPACKER_XYZ`.
```
- Rename environment variables in the format of `WEBPACKER_XYZ` to `SHAKAPACKER_XYZ`.

2023-03-10 21:13 UTC, justin808 commented on docs/v7_upgrade.md
> +#### server options
```
### Binstub Options
```

2023-03-10 21:13 UTC, justin808 commented on docs/v7_upgrade.md
> +- If you use `--debug-webpacker` for your `bin/webpacker` or `bin/webpacker-dev-server`, now you should use `--debug-shakapacker`.
```
- `--debug-webpacker` is now `--debug-shakapacker` for your shakpacker binstubs.
```

2023-03-10 21:13 UTC, justin808 commented on docs/v7_upgrade.md
> +If you have successfully upgraded to version 6.6.x and have no deprecation message in your console, You should be all set to upgrade your Shakapacker to version 7. Details on this upgrade will be add
```
Once you have successfully upgraded to version 6.x and have no deprecation messages in your console, you should be ready to upgrade Shakapacker to version 7. Check the [CHANGELOG](../CHANGELOG.md) for additional details.
```

2023-03-10 21:13 UTC, justin808 commented on lib/shakapacker/configuration.rb
> +    end
This logic needs testing. Code is unclear.

2023-03-10 21:13 UTC, justin808 commented on lib/shakapacker/configuration.rb
> +    end
is this what you're trying?

or just check if key matches `webpacker` and transform key to use `shakapacker`.

```rb
    # for backward compatibility
    if data.key?(:webpacker_precompile)
      Shakapacker.puts_deprecation_message(
        Shakapacker.short_deprecation_message(
          "webpacker_precompile",
          "shakapacker_precompile"
        )
       return data.fetch(:webpacker_precompile) 
      )
    end

    return data.fetch(key, defaults[key]) 
```

2023-03-10 21:13 UTC, justin808 commented on lib/shakapacker/deprecation_helper.rb
> +
```
    Using webpacker spelling is deprecated in Shakapacker. Update your project with the new spelling.
``

2023-03-10 21:13 UTC, justin808 commented on lib/shakapacker/deprecation_helper.rb
> +      webpacker_config_path = if config_path.class == Pathname
not formatted correctly

2023-03-10 21:13 UTC, justin808 commented on package/rules/__tests__/__utils__/webpack.js
> +const app_javascript = path.resolve("app/javascript");
this seems unrelated to this PR

Just a useful fix?

2023-03-11 10:00 UTC, ahangarha commented on .github/workflows/ruby-backward-compatibility.yml
> +        ruby: ['2.6', '2.7', '3.0']
@justin808 
What about this?

2023-03-11 11:42 UTC, ahangarha commented on lib/shakapacker/configuration.rb
> +    webpacker_key = key.to_s.gsub("shakapacker", "webpacker").to_sym
This part is rewritten entirely

2023-03-11 12:00 UTC, ahangarha commented on lib/shakapacker/configuration.rb
> +    end
This was a part of it but also there are some edge cases.

Imagine a scenario in which we have an old project. We call `Webpacker.config.webpacker_precompile?`. This method shows a deprecation message and internally runs `shakapacker_precompile?` method. This ends in calling `fetch(:shakapacker_precompile)` while we are still in an old setup. So unlike many other places, in this case we shouldn't assume if we get `shakapacker...` key, it means we are already in a new setup.

I have updated this part of the code and I think it covers all scenarios. Though we don't have enough tests to cover all scenarios.

2023-03-11 12:15 UTC, ahangarha commented on package/rules/__tests__/__utils__/webpack.js
> +const app_javascript = path.resolve("app/javascript");
I needed to fix it to pass CI.
I am not sure why CI was passing in its own PR. Actually, app_javascript should point to the source_path otherwise, webpack wouldn't pick it up.

2023-03-11 12:19 UTC, ahangarha commented on lib/tasks/shakapacker/check_binstubs.rake
> +         - Ensure the `bin` directory and `bin/shakapacker` are not included in .gitignore.
I am not getting the reason

2023-03-14 23:14 UTC, justin808 requested changes

2023-03-14 23:14 UTC, justin808 commented on CHANGELOG.md
> +- Rename Webpacker to Shakapacker in entire project including config files, binstubs, environment variables,... with backward compatibility [PR157](https://github.com/shakacode/shakapacker/pull/157)
reference migration doc

2023-03-14 23:14 UTC, justin808 commented on lib/shakapacker/configuration.rb
> +    @config_path = Pathname.new(ENV["SHAKAPACKER_CONFIG"] || config_path)
was this done somewhere else in a prior PR?

2023-03-14 23:14 UTC, justin808 commented on lib/shakapacker/configuration.rb
> +    end
Correct.

2023-03-14 23:14 UTC, justin808 commented on lib/shakapacker/configuration.rb
> +    return data.fetch(key, defaults[key])
Let's invert this as it's the common case

```rb
return data.fetch(key, defaults[key]) unless key == :webpacker_precompile

...
```

2023-03-14 23:24 UTC, ahangarha commented on lib/shakapacker/configuration.rb
> +    @config_path = Pathname.new(ENV["SHAKAPACKER_CONFIG"] || config_path)
Which line? 

If 17, no.

For line no.18, I found it challenging to set config path from env when we do it in Instance class. This way, I let the configuration class make the final decision about the config path.

Perhaps it was better to do it in the renaming PR. Yet, this is just internal change.

2023-03-15 20:07 UTC, ahangarha commented on lib/shakapacker/configuration.rb
> +    return data.fetch(key, defaults[key])
Much better. Thanks 👍🏾

2023-03-15 20:15 UTC, ahangarha commented on lib/shakapacker/deprecation_helper.rb
> +      webpacker_config_path = if config_path.class == Pathname
Rubocop forces me to use such indentation. We have this rule:
```
Use 2 (not 26) spaces for indentation.
(convention:Layout/IndentationWidth)
```

2023-03-17 07:08 UTC, justin808 approved these changes

2023-03-17 07:09 UTC, merged