Set CSS modules mode depending on file type
shakacode/shakapacker pull request #261
Opened 2023-03-10 22:20 UTC by talyuk

### Summary
Set CSS modules mode to `icss` if a style file is not a module, `local` otherwise. It allows using `ICSS` features such as `:import` and `:export` without using further `CSS Module` functionality. ICSS features were applied by default to all files before `css-loader@v4`, but it's been changed in the next versions. (Please refer to `css-loader` [example](https://github.com/webpack-contrib/css-loader#separating-interoperable-css-only-and-css-module-features))

2023-03-17 07:27 UTC, justin808 commented on package/utils/get_style_rule.js
> +            mode: resourcePath => isModuleFile(resourcePath) ? 'local' : 'icss'
Why or why not could we use the  `auto: true`

https://github.com/webpack-contrib/css-loader#auto 

```
        options: {
          modules: {
            auto: true,
          },
        },
```

2023-03-23 22:35 UTC, justin808 commented on package/utils/get_style_rule.js
> +            mode: resourcePath => isModuleFile(resourcePath) ? 'local' : 'icss'
@talyuk any comment?

2023-03-30 09:54 UTC, alex35mil commented on package/utils/get_style_rule.js
> +            mode: resourcePath => isModuleFile(resourcePath) ? 'local' : 'icss'
I skimmed through the docs, and it seems that `auto: true` is the best choice for this case since users should be familiar with the behavior and it already does what's proposed in this PR (correct me if I'm wrong). @talyuk What do you think?

2023-04-03 09:07 UTC, tomdracz requested changes

2023-04-03 09:07 UTC, tomdracz commented on package/utils/get_style_rule.js
> +            mode: resourcePath => isModuleFile(resourcePath) ? 'local' : 'icss'
+1 `auto: true` is the sensible choice here

2023-04-04 08:08 UTC, justin808 commented
@tomdracz or @talyuk, can you submit a PR with `auto: true`?

2023-04-04 11:11 UTC, tomdracz commented
Updated to use `auto: true` in this PR

2023-04-04 11:12 UTC, tomdracz approved these changes

2023-04-05 07:59 UTC, merged