WIP - Update webpack dev server configuration
shakacode/shakapacker pull request #276
Opened 2023-04-04 13:01 UTC by ahangarha

### Summary

This PR adds/modify dev server based on standard webpack dev server configuration.

### Pull Request checklist
- [ ] Add/update test to cover these changes
- [ ] Update documentation
- [ ] Update CHANGELOG file

### Other Information

closes #217

2023-04-11 02:59 UTC, justin808 commented on lib/install/config/shakapacker.yml
> +    server: http
what happens if this is not updated when v7 is installed?

2023-04-11 02:59 UTC, justin808 commented on package/environments/development.js
> +    server: devServer.server,
what happens if this is not updated when v7 is installed?

for both changes, we'll default to the these files in this PR

2023-04-11 02:59 UTC, justin808 commented on CHANGELOG.md
> +  - Deprecated `https` entry is removed from the default configuration file, allowing to set `server` or `https` as per the project requirements. For more detail, check Webpack documentation. The `ht
can you put a link to the docs?

2023-04-11 02:59 UTC, justin808 commented on CHANGELOG.md
> +- All standard Webpack entries with the camle-case format are now supported in `shakapacker.yml` in snake-case format. [PR276](https://github.com/shakacode/shakapacker/pull/276) by [ahangarha](https:
camel

2023-04-11 02:59 UTC, justin808 commented on CHANGELOG.md
> +- All standard Webpack entries with the camle-case format are now supported in `shakapacker.yml` in snake-case format. [PR276](https://github.com/shakacode/shakapacker/pull/276) by [ahangarha](https:
`camelCase` and `snake_case`

2023-04-11 02:59 UTC, justin808 commented on package/environments/development.js
> +    ['magicHtml', 'magic_html'],
what are these?

2023-04-11 02:59 UTC, justin808 commented on package/environments/development.js
> +  } else if (devServer.https) {
is this changed on this line: https://github.com/shakacode/shakapacker/pull/276/files#diff-25bf6d99ed3e46a999883db9154223cf0a4c2c41e366c953652e597ded0561feR25

2023-04-11 11:18 UTC, ahangarha commented on lib/install/config/shakapacker.yml
> +    server: http
Nothing happens.

We read both of these values if they are provided in the config files. If not, we set them to `http`. But instead of relying on one of them, we rely on `protocol` which is calculated based on these two. There, the priority is with `server` to be `https`, otherwise we check if `https` is set to `true`. If not, we set `protocol` to be `http`.

This way, the old configuration still works so hypothetically we don't break anything.

I have written tested for all the above mentioned situations.

2023-04-11 11:28 UTC, ahangarha commented on CHANGELOG.md
> +  - Deprecated `https` entry is removed from the default configuration file, allowing to set `server` or `https` as per the project requirements. For more detail, check Webpack documentation. The `ht
I have included link to Webpack dev-server documentation. If you mean a link to Shakapcker documentation, I don't think we need to. Because this is very much related to Webpack configuration. If you think we need to have dedicated documentation for the Shakapacker configuration, then I can explore that.

2023-04-11 11:29 UTC, ahangarha commented on CHANGELOG.md
> +- All standard Webpack entries with the camle-case format are now supported in `shakapacker.yml` in snake-case format. [PR276](https://github.com/shakacode/shakapacker/pull/276) by [ahangarha](https:
I shouldn't have missed it. Thanks for noticing.

2023-04-11 11:38 UTC, ahangarha commented on package/environments/development.js
> +    ['magicHtml', 'magic_html'],
At the moment we don't use these entries. But if we do, either we should use add them in camelCase or Webpack cannot detect them. So in order to support them in Shakapacker, I made this array, so we can set the right camelCase entry for Webpack if they are set in snake_case in `shakapacker.yml`.

Somehow we do the same thing above these lines, assuming they are all set, so we map the values one by one. I just did the same thing in a DRY way.

2023-04-11 11:52 UTC, ahangarha commented on package/environments/development.js
> +    server: devServer.server,
Actually, this had to be removed after I added the code in line 44.
I had to write tests (the way I did TDD on the Ruby side) to prevent such mistakes.

2023-04-11 11:53 UTC, ahangarha commented on package/environments/development.js
> +  } else if (devServer.https) {
Yes. Exactly.
I had to remove that line after these new ones.

2023-04-11 14:45 UTC, justin808 requested changes
Please let me know when ready to merge.

2023-04-11 14:45 UTC, justin808 commented on lib/shakapacker/dev_server.rb
> +  rescue
this swallows all exceptions such as a typo

please always catch specific errors

2023-04-11 17:36 UTC, ahangarha commented
@justin808 
I think all the code related to modifying `dev_server` configuration should move out from `development.rb` into `Shakapacker::DevServer` class.

Am I right?

2023-04-12 16:37 UTC, ahangarha commented
I have made some refactoring.

- I moved all the code related to processing devServer entries into `dev_server.js`.
- There, after setting a few particular entries, I map all the entries from the original config file into devServer object. There, I map all the Webpack-specific keys into keys in camelCase format. Any other Webpack non-specific keys get copied without any change.

2023-04-12 16:40 UTC, ahangarha commented on lib/shakapacker/dev_server.rb
> +  rescue
Done

2023-04-15 02:45 UTC, justin808 approved these changes
lgtm

2023-04-15 02:47 UTC, merged