Pass config as hash new
shakacode/shakapacker pull request #285
Opened 2023-04-20 11:59 UTC by ahangarha

### Summary

This PR attempts to implement requirements of #279.

⚠️ NOTE: This PR has several breaking changes!

Objectives:
- Pass config hash instead of the path to config file while initializing Shakapacker instance and configuration.
- Follow SRP by extracting logic for reading and converting the content of config files.

### Pull Request checklist

- [ ] Add/update test to cover these changes
- [ ] Update documentation
- [ ] Update CHANGELOG file

### Other Information

One of my attempts was to combine the custom configs (provided by the developer, read from the config file in the project by default) with the default configs (read from the config file in the gem by default). This way, the entries in the default config replace the missing entry in the provided config hash. This decision has an impact on several entries. Though I think this is the correct implementation, we must decide whether the default config should fill in the missing entries in the custom config.

Some of the failing tests are examples of these changes. I have added TODO notes in relevant spots to make it easier to understand the cause.

Closes #279

2023-04-25 21:37 UTC, justin808 requested changes

2023-04-25 21:37 UTC, justin808 commented on lib/shakapacker/compiler.rb
> +              )
If it's not needed, that's fine. Just remove the comments. And indicate removal in the CHANGELOG.

2023-04-25 21:37 UTC, justin808 commented on lib/shakapacker/configuration.rb
> +      config_path = ENV["SHAKAPACKER_CONFIG"] ? Pathname.new(ENV["SHAKAPACKER_CONFIG"]) : Rails.root.join("config/shakapacker.yml")
I like to use `.presence?` because "" is truth in ruby

2023-04-25 21:37 UTC, justin808 commented on lib/shakapacker/configuration.rb
> +    # TODO: Following commented line doesn't make sense! If we don't set
👍

2023-04-25 21:37 UTC, justin808 commented on lib/shakapacker/configuration.rb
> +      full_config = HashWithIndifferentAccess.new(@default_config.deep_merge(@custom_config))
2 lines is better.

```rb
combined_config = @default_config.deep_merge(@custom_config)
```

2023-04-25 21:37 UTC, justin808 commented on lib/shakapacker/configuration.rb
> +      full_config[env] || full_config[Shakapacker::DEFAULT_ENV]
this is too subtle

fallback to default env should issue a warning

and what if the env == default_env and full_config has no value

2023-04-25 21:37 UTC, justin808 commented on lib/shakapacker/dev_server.rb
> +      ENV["#{env_prefix}_#{key.upcase}"] || config.dev_server.fetch(key)
looks like duplicated lines

2023-04-25 21:37 UTC, justin808 commented on lib/shakapacker/helper.rb
> +        end
I don't like the above error handling. Always log errors.

2023-04-26 08:11 UTC, ahangarha commented on lib/shakapacker/configuration.rb
> +    # TODO: Following commented line doesn't make sense! If we don't set
This is a breaking change. In past, we were returning false if the was no config file. Not sure what was the logic for not trying to load value from the default config. As a result, with a wrong path, we would return `false`, but now since we handle reading and parsing the config file separately, we cannot apply this logic. I think the old logic and test for it was not helpful at all.

Now we will handle invalid config paths in a different place and in a different way. We need to modify tests to cover the new (and supposedly more appropriate) implementation.

2023-04-26 08:25 UTC, ahangarha commented on lib/shakapacker/compiler.rb
> +              )
I found this part (setting and using `SHAKAPACKER_CONFIG`) tricky.

Now that I know the overall implementation is in the right direction, I check this more carefully.

2023-04-26 08:35 UTC, ahangarha commented on lib/shakapacker/configuration.rb
> +      full_config[env] || full_config[Shakapacker::DEFAULT_ENV]
What if we see the custom confg as a way to modify the default configuration? We can have a long list of default configurations and then override entries as we need, using the custom hash.

This way, we don't need to warn for falling back to the default config (as we never did in the past). Almost the only difference here is that now we fall back to defaults in a much more robust and predictable.

The last question is a good one! I was thinking about it in the wrong place (fall back in the `fatch` method). I think we should return nil if we want to get a value of a non-existing config entry. We can also issue a warning message for such an attempt.

2023-04-26 08:42 UTC, ahangarha commented on lib/shakapacker/helper.rb
> +        end
What should happen if the path doesn't exist? My answer is to break the program and issue an error in the terminal. We shouldn't continue at all.

---

Generally this is not a right place for this function. As I understand, this file is a view helper. I need to move this function somewhere out of this file but still now sure where.

2023-04-27 12:32 UTC, ahangarha commented on lib/shakapacker/configuration.rb
> +      config_path = ENV["SHAKAPACKER_CONFIG"] ? Pathname.new(ENV["SHAKAPACKER_CONFIG"]) : Rails.root.join("config/shakapacker.yml")
@justin808 
This is the interface I thought about:

- `nil`: load from `config/shakapacker.yml`
- `{}`: no custom config --> apply default config
- `{...}`: the config to override the default config

We need to decide carefully on the new interface.

2023-04-29 06:41 UTC, ahangarha commented on lib/shakapacker/helper.rb
> +      else
@justin808 
What about using env variables to set and track the state of installation?

2023-05-01 12:13 UTC, ahangarha commented on lib/shakapacker/helper.rb
> +      else
I have implemented what I said. I also added backward compatibility to be in a safe margin. I don't think we really need backward compatibility for this since this logic is used only during installation.

2023-05-02 17:05 UTC, ahangarha commented on lib/shakapacker/helper.rb
> +        end
I changed this part so we raise an error if the given file path is invalid. We don't return any configuration in such cases.

2023-05-02 20:01 UTC, justin808 commented on CHANGELOG.md
> +- `Shakapacker::Configuration.installing` is deprected in favor or using `SHAKAPACKER_INSTALLING` environment variable. [PR 285](https://github.com/shakacode/shakapacker/pull/285) by [ahangarha](http
Why? https://github.com/shakacode/shakapacker/commit/ce7cdd707f79065d975c2005d14ec821df30e3b1

2023-05-03 08:18 UTC, ahangarha commented on CHANGELOG.md
> +- `Shakapacker::Configuration.installing` is deprected in favor or using `SHAKAPACKER_INSTALLING` environment variable. [PR 285](https://github.com/shakacode/shakapacker/pull/285) by [ahangarha](http
The logic for replacing `Shakapacker::Configuration.installing` with `SHAKAPACKER_INSTALLING` was to reduce the coupling between this function and Shakapacker's implementation. If it is not needed, then I can revert it.

2023-05-05 02:46 UTC, justin808 commented
Right now, too many changes for questionable benefit.

2023-05-08 22:13 UTC, closed without merging