WIP - Add generator test
shakacode/shakapacker pull request #300
Opened 2023-05-19 22:38 UTC by ahangarha

### Summary

Add test to ensure `rails shakapacker:install` works as expected.

### Pull Request checklist

- [ ] Add/update test to cover these changes
- [ ] Update documentation
- [ ] Update CHANGELOG file

### Other Information
- All other CIs are removed temporarily
- While tests failed in this [CI run](https://github.com/shakacode/shakapacker/actions/runs/5028751244), it shows a green check.
- At the time of writing this description, CI fail in Ruby 3.1.2.

Todo:
- [ ] Install a minimal fresh Rails application for this test rather than using a pre-build app.
- [ ] Update CI to work with different Ruby and Rails versions.

2023-05-22 19:10 UTC, justin808 commented on .github/workflows/generator.yml
>            - gemfiles/Gemfile-rails.5.2.x
get rid of Rails 5 as well

2023-05-22 22:28 UTC, ahangarha commented on .github/workflows/generator.yml
>            - gemfiles/Gemfile-rails.5.2.x
Done

In #301 I remove Rails 5 entirely.

2023-05-23 04:18 UTC, justin808 commented on spec/generator_specs/generator_spec.rb
> +end
After running the generator, you want to add a basic react component with or without React on Rails and then run some system/feature spec.

2023-06-06 13:43 UTC, ahangarha commented on spec/generator_specs/generator_spec.rb
> +end
Added!

2023-06-06 21:40 UTC, Judahmeek requested changes

2023-06-06 21:40 UTC, Judahmeek commented on spec/generator_specs/generator_spec.rb
> +      context "with a basic react app setup" do
What's the difference between this & the "normal" rails app?

2023-06-06 21:40 UTC, Judahmeek commented on CHANGELOG.md
> +- Fixed the bug in adding correct rc release to the `package.json` in `shakapacker:install` task [PR300](https://github.com/shakacode/shakapacker/pull/300) by [ahangarha](https://github.com/ahangarha
Justin prefers that bug fixes have separate PRs if possible

2023-06-06 21:40 UTC, Judahmeek commented on CHANGELOG.md
> +- The `shakapacker:install` rake task now has an option to force overriding files using `FORCE=true` environment variable [PR300](https://github.com/shakacode/shakapacker/pull/300) by [ahangarha](htt
Justin prefers that new functionality have separate PRs if possible

2023-06-06 21:40 UTC, Judahmeek commented on lib/install/template.rb
> +  end
I don't think this is right.

The reason some PeerDependencies are listed as devDependencies in Shakapacker's package.json is because they are also essential for development and/or testing.

However, if they get listed as devDependencies in the user's package.json, then they won't be installed by most production scripts, such as Heroku's setup.

So we definitely don't want packages that are listed as devDependencies in Shakapacker's package.json to be listed as devDependencies in the user's package.json.

2023-06-06 21:40 UTC, Judahmeek commented on lib/install/template.rb
> +  results << run("yarn add --dev #{dev_dependencies_to_add.join(' ')}")
We want to install webpack-dev-server & probably only webpack-dev-server as a devDependency because it is never supposed to be used in production.

2023-06-07 06:50 UTC, ahangarha commented on lib/install/template.rb
> +  end
To clarify, peer dependencies in Shakapacker include `webpack-dev-server`. Currently we install all of them as `dependencies` and then try to install `webpack-dev-server` as `devDependency`, which never happens because it is already added to the `dependencies`.

What should we do with it? would we keep `webpack-dev-server` in dependencies? If so, then we should remove the code in installing it as a dev dependency.

2023-06-07 06:52 UTC, ahangarha commented on lib/install/template.rb
> +  results << run("yarn add --dev #{dev_dependencies_to_add.join(' ')}")
That is what I have done. `dev_dependencies_to_add` contains only `webpack-dev-server`. I made it like this to be more clear about what is going on and also have the option to add other dev dependencies in the future if needed.

If you think I made it complex to understand, then I failed in achieving my goal.

2023-06-07 06:56 UTC, ahangarha commented on spec/generator_specs/generator_spec.rb
> +      context "with a basic react app setup" do
By "normal rails app" I meant a rails app without any issues. I made that context so we can add another context for problematic setups to verify `shakapacker:install` gives correct error messages when faced with malformatted files.

This react setup is a new context within the "normal" Rails app context

2023-06-07 06:57 UTC, ahangarha commented on CHANGELOG.md
> +- Fixed the bug in adding correct rc release to the `package.json` in `shakapacker:install` task [PR300](https://github.com/shakacode/shakapacker/pull/300) by [ahangarha](https://github.com/ahangarha
Surly I can extract these commits to its own PR.
I just kept it here because I didn't want to get my further development blocked.

2023-06-07 06:57 UTC, ahangarha commented on CHANGELOG.md
> +- The `shakapacker:install` rake task now has an option to force overriding files using `FORCE=true` environment variable [PR300](https://github.com/shakacode/shakapacker/pull/300) by [ahangarha](htt
Surly I can extract these commits to its own PR.
I just kept it here because I didn't want to get my further development blocked.

2023-06-08 15:38 UTC, ahangarha commented on CHANGELOG.md
> +- Fixed the bug in adding correct rc release to the `package.json` in `shakapacker:install` task [PR300](https://github.com/shakacode/shakapacker/pull/300) by [ahangarha](https://github.com/ahangarha
Created #312

2023-06-08 15:39 UTC, ahangarha commented on CHANGELOG.md
> +- The `shakapacker:install` rake task now has an option to force overriding files using `FORCE=true` environment variable [PR300](https://github.com/shakacode/shakapacker/pull/300) by [ahangarha](htt
Created #311

2023-06-08 15:43 UTC, ahangarha commented
@Judahmeek @justin808 
To keep this PR focused only on tests, I have split this PR into multiple smaller PRs: #310, #311, and #312.

Please review.

After merging them, I should push a cleaned-up commit history of this PR.

2023-06-09 16:40 UTC, Judahmeek requested changes

2023-06-09 16:40 UTC, Judahmeek commented on lib/install/template.rb
> +  end
My mistake. I misread the code.

I jumped to the conclusion that `if dev_dependencies.include? package` meant that it was from the package.json's list of `devDependencies`, not from `dev_dependencies = ["webpack-dev-server"]`

I think I would change the above code to
```
  dev_dependencies_to_add = ["webpack-dev-server"]

  dependencies_to_add = []

  peers.each do |(package, version)|
    next if dev_dependencies.include? package
    major_version = version.match(/(\d+)/)[1]
    entry = "#{package}@#{major_version}"
    dependencies_to_add << entry
  end
  ```
  The main reason for the change is that having both the `dev_dependencies` & `dev_dependencies_to_add` arrays is a little redundant.

2023-06-09 16:44 UTC, ahangarha commented
@Judahmeek 
> The main reason for the change is that having both the dev_dependencies & dev_dependencies_to_add arrays is a little redundant.

You are absolutely right. Actually, if I am going to create `dev_dependencies` array here, then there is no point in making `dev_dependencies_to_add`. I should name it `dev_dependencies_to_add` and exclude them from `dependencies_to_add`.

I am not satisfied with the solution, but I don't know any other way to derive dev dependencies from the list of peer dependencies.

2023-06-10 16:46 UTC, Judahmeek approved these changes

2023-06-10 16:49 UTC, merged