Wrap up version 7 changes
shakacode/shakapacker pull request #301
Opened 2023-05-22 17:11 UTC by ahangarha

### Summary

Some minor changes before getting Shakapacker 7 shipped. Key changes:

Todos:
- [x] Move `test_app` to `shakapacker` directory
- [x] Reorganize Changelog

2023-05-23 04:22 UTC, justin808 requested changes
Only one small comment to address.

2023-05-23 04:22 UTC, justin808 commented on CONTRIBUTING.md
> +If looking for contributing to the project by fixing existing issues, we recommend looking at closed issues, particularly with the "[help wanted](https://github.com/shakacode/shakapacker/issues?q=is%
Maybe mention webpacker as well, but, TBH, issues worth fixing should NOT be marked as closed. So I question this advice. I'd say look at any issues with help wanted, but first open issues.

2023-05-23 04:22 UTC, justin808 commented on CONTRIBUTING.md
> +      yalc push # or yalc publish --push
type changes above line 44

why not always the publish option?

2023-05-23 10:10 UTC, ahangarha commented on CONTRIBUTING.md
> +If looking for contributing to the project by fixing existing issues, we recommend looking at closed issues, particularly with the "[help wanted](https://github.com/shakacode/shakapacker/issues?q=is%
You are right. I think at one point we closed them to increase focus. We should take them back.

2023-05-23 10:11 UTC, ahangarha commented on CONTRIBUTING.md
> +If looking for contributing to the project by fixing existing issues, we recommend looking at closed issues, particularly with the "[help wanted](https://github.com/shakacode/shakapacker/issues?q=is%
By the way, this text was there. I just moved it up.

2023-05-23 10:13 UTC, ahangarha commented on CONTRIBUTING.md
> +      yalc push # or yalc publish --push
Using `yalc push` updates all the projects using the package.

2023-05-26 01:22 UTC, justin808 commented
@ahangarha  can I merge?

2023-05-30 14:03 UTC, ahangarha commented
@justin808 Let's keep this open for minor changes that won't change anything substantial. That was the idea for making this branch and draft PR.

2023-05-30 14:06 UTC, ahangarha commented on CONTRIBUTING.md
> +If looking for contributing to the project by fixing existing issues, we recommend looking at closed issues, particularly with the "[help wanted](https://github.com/shakacode/shakapacker/issues?q=is%
@justin808 May you please check the closed [help wanted](https://github.com/shakacode/shakapacker/issues?q=is%3Aissue+label%3A%22help+wanted%22+is%3Aclosed+) issues and see if we should include any of them in version 7 (as a breaking change)? For example, I just noticed you mentioned #143 to be added in version 7.

2023-06-12 16:49 UTC, merged