Fix check binstubs task by removing exit
shakacode/shakapacker pull request #307
Opened 2023-05-26 17:40 UTC by ahangarha

### Summary

Because of exiting from `shakapacker:binstubs`, `shakapacker:verify_install` couldn't pass. As a result, `shakapacker:compile` couldn't be added to `assets:precompile` task.

### Pull Request checklist

- [ ] Add/update test to cover these changes
- [ ] Update documentation
- [ ] Update CHANGELOG file

### Other Information

This PR should resolve and close #305 issue.

2023-05-27 15:02 UTC, ahangarha commented
@justin808 Should we add tests for our rake task to ensure the chain of tasks works fine?

2023-05-30 06:56 UTC, justin808 requested changes

2023-05-30 06:56 UTC, justin808 commented on lib/tasks/shakapacker/check_binstubs.rake
> +      # pass
you can't just have an if with no statement

did you test if this runs OK?

Just put all the code below in an 

```rb
unless File.exist?(Rails.root.join("bin/shakapacker"))
    elsif File.exist?(Rails.root.join("bin/webpacker"))
      Shakapacker.puts_deprecation_message(
        Shakapacker.short_deprecation_message(
          "bin/webpacker",
          "bin/shakapacker"
        )
      )
      # pass
    else
      puts <<~MSG
        Could't find shakapacker binstubs!
        Possible solutions:
         - Ensure you have run `rails shakapacker:install`.
         - Run `rails shakapacker:binstubs` if you have already installed shakapacker.
         - Ensure the `bin` directory and `bin/shakapacker` are not included in .gitignore.
      MSG
      exit!
    end
  end
end

2023-05-30 06:56 UTC, justin808 requested changes
see comment

2023-05-30 09:50 UTC, ahangarha commented on lib/tasks/shakapacker/check_binstubs.rake
> +      # pass
Wow! Much much better code.
Thanks

2023-05-30 09:53 UTC, ahangarha commented on lib/tasks/shakapacker/check_binstubs.rake
> +      # pass
@justin808 
Perhaps not a bad idea to also include `shakapacker-dev-server` in the check. We didn't have it in the past, but why not include it now?

2023-05-30 11:10 UTC, ahangarha commented on lib/tasks/shakapacker/check_binstubs.rake
> +      # pass
@justin808 
- Fixed the issue you mentioned,
- Included the check for `bin/shakapacker-dev-server`
- Added specs for different scenarios

2023-06-06 07:48 UTC, merged