feat: support passing config to `generateWebpackConfig` for merging
shakacode/shakapacker pull request #343
Opened 2023-08-05 02:43 UTC by G-Rath

### Summary

Enables providing `generateWebpackConfig` an optional object that is included in the config merge, reducing the amount of boilerplate code you have to write when doing basic customization to the config.

### Pull Request checklist
- [x] Add/update test to cover these changes
- [x] Update documentation
- [x] Update CHANGELOG file

### Other Information

Resolves #329

2023-08-05 12:51 UTC, ahangarha approved these changes
It's a good proposal with a clean implementation.

It would be good to update the current dummy app based on these changes.

✅ Added tests
✅ Updated Documentation
🚫 Updated Changelog

Please update the changelog.

@justin808 Should we prepare for `7.1.0`?

2023-08-05 12:51 UTC, ahangarha requested changes
It's a good proposal with a clean implementation.

It would be good to update the current dummy app based on these changes.

white_check_mark Added tests
✅ Updated Documentation
🚫 Updated Changelog

Please update the changelog.

@justin808 Should we prepare for 7.1.0?

2023-08-07 13:18 UTC, ahangarha requested changes
Thanks for applying the changes. It looks good.

We just have an issue with passing multiple configs. Check my comment.

2023-08-07 13:18 UTC, ahangarha commented on spec/dummy/config/webpack/commonWebpackConfig.js
> +const commonWebpackConfig = () => generateWebpackConfig(commonOptions, ignoreWarningsConfig)
The current definition of `generateWebpackConfig` accepts only one argument. Here, we pass two meaning we will miss the second extra configuration.

I think it good to make `generateWebpackConfig` accept multiple configs and apply them in the given order.

2023-08-11 20:58 UTC, justin808 requested changes

2023-08-11 20:58 UTC, justin808 commented on package/index.js
>    const environmentConfig = globalMutableWebpackConfig()
Let's throw an error if there is more than one arg.

2023-08-13 06:57 UTC, ahangarha commented on spec/dummy/config/webpack/commonWebpackConfig.js
> +const commonWebpackConfig = () => generateWebpackConfig(commonOptions, ignoreWarningsConfig)
As per [Justin's comment](https://github.com/shakacode/shakapacker/pull/343#discussion_r1291768853), we can consider merging "extra configs" before passing them to `generateWebpackConfig()`.

2023-08-14 19:31 UTC, G-Rath commented
Thanks for the reviews - I'll action them in the next couple of weeks as I'm working on #349 right now

2023-08-29 03:38 UTC, justin808 commented
@G-Rath Ping me when ready for review!

2023-08-31 23:23 UTC, justin808 commented on README.md
> +module.exports = generateWebpackConfig(options)
1. It's not clear where to place this code. What file is this?
2. With the new object rather than global, some people might get confused if they are migrating old code of multiple files that simply mutated the global object.

2023-08-31 23:23 UTC, justin808 commented on README.md
> +module.exports = generateWebpackConfig(options)
These changes might be fine as-is...just some thoughts.

2023-08-31 23:46 UTC, G-Rath commented on README.md
> +module.exports = generateWebpackConfig(options)
@justin808 I've reworded the documentation to make it clearer where the file lives. I'm not sure what you mean by your second point though?

2023-09-03 05:41 UTC, justin808 approved these changes
LGTM. Merge?

2023-09-03 06:03 UTC, G-Rath commented
Yup go for it! It would also be good to get released :)

2023-09-04 22:18 UTC, justin808 requested changes

2023-09-04 22:18 UTC, justin808 commented on package/index.js
> +  if (extraArgs.length) {
can you add `> 0` for readability? Yes, this works in JS and not in Ruby!

2023-09-04 22:22 UTC, G-Rath commented on package/index.js
> +  if (extraArgs.length) {
Sure thing

```suggestion
  if (extraArgs.length > 0) {
```

2023-09-05 07:11 UTC, justin808 approved these changes

2023-09-05 07:12 UTC, merged