WIP - feat: make compilation stale on asset host change
shakacode/shakapacker pull request #364
Opened 2023-10-04 12:32 UTC by ahangarha

### Summary

This PR adds a feature for making digest strategy sensitive towards asset_host change. This way, by changing `SHAKAPACKER_ASSET_HOST`, we get new asset compilation.

This is an opt-in feature.

### Pull Request checklist
- [x] Add/update test to cover these changes
- [ ] Update documentation
- [ ] Update CHANGELOG file

### Other Information

Closes #328

2023-10-05 03:50 UTC, Judahmeek approved these changes
LGTM. Just have one question.

2023-10-05 03:50 UTC, Judahmeek commented on lib/shakapacker/digest_strategy.rb
> +      def generate_host_hash(*keys)
Why did you enable `generate_host_hash` to take parameters when you don't provide parameters when `generate_host_hash` is called by `compilation_digest_path` or for any sort of testing?

2023-10-05 06:41 UTC, ahangarha commented on lib/shakapacker/digest_strategy.rb
> +      def generate_host_hash(*keys)
Good point!

I thought of different ways of implementation. And with this implementation, there is no need to take arguments.

In general, I like to make pure functions as much as possible. But, in this case, the method can be unpure as a private method.

I will remove the arguments.

2023-10-05 07:51 UTC, ahangarha commented
@Judahmeek 
There was an issue with memoization. I fixed it. Now it only runs the digest algorithm once.

2023-10-15 03:17 UTC, justin808 commented on lib/install/config/shakapacker.yml
> +  compiler_strategy_asset_host_sensitive: false
I don't think this is necessary. If the asset host changes, recompile. Why have an option?

2023-10-15 18:21 UTC, ahangarha commented on lib/install/config/shakapacker.yml
> +  compiler_strategy_asset_host_sensitive: false
Not setting it off by default, we get failed tests for backward compatibility.
I'll check it again.

2023-10-16 10:36 UTC, ahangarha commented on lib/install/config/shakapacker.yml
> +  compiler_strategy_asset_host_sensitive: false
I added [4082109](https://github.com/shakacode/shakapacker/pull/364/commits/40821094c15ddf74b9ad8fc2b59bfa42ccd8131a) where I simplify the logic, removed the mentioned config entry, and yet get the same result:
- If there is no `asset_host` and `SHAKAPACKER_ASSET_HOST`, we don't touch the path.
- Otherwise, we add a computed hash based on the combination of the two mentioned values to the path.

2023-10-19 00:37 UTC, justin808 requested changes

2023-10-19 00:37 UTC, justin808 commented on lib/shakapacker/digest_strategy.rb
> +        keys = [Rails.application.config.asset_host, ENV["SHAKAPACKER_ASSET_HOST"]]
This improper.

Create a method for this code:
https://github.com/shakacode/shakapacker/blob/28a969a36e3757d6dc22317bda5dda447bfcd4a3/lib/shakapacker/compiler.rb#L109

that way you dry up the logic.

then you just have one simple string value for those host hash

and when you change either configs or ENVs, you **HAVE** to restart, so no need for hash for the memoization.

2023-10-19 00:37 UTC, justin808 commented on lib/shakapacker/digest_strategy.rb
> +        path += "-#{generate_host_hash}" if generate_host_hash.present?
no need for 2 lines and the if statement...

code below never returns nil for the method call.

2023-10-25 08:37 UTC, ahangarha reviewed
Based on my comments, I wonder if we are testing the actual behavior of Shakapacker. In actual apps, I couldn't get any value for `Shakapacker::Compiler.env` except an empty hash.

2023-10-25 08:37 UTC, ahangarha commented on lib/shakapacker/digest_strategy.rb
> +        if Shakapacker::Compiler.env["SHAKAPACKER_ASSET_HOST"].present?
I tried in different ways to get the value of this `Shakapacker::Compiler.env` but in all cases, I got an empty hash. If we cannot access the value, then it means the code inside this condition never gets running.

Either my approaches were wrong or we need to investigate `Shakapacker::Compiler.env` deeper.

2023-10-25 08:37 UTC, ahangarha commented on spec/shakapacker/digest_strategy_spec.rb
>    end
Regarding my other comment, I am afraid we get false positive test passages with such tests.

2023-10-27 02:43 UTC, justin808 commented on lib/shakapacker/digest_strategy.rb
> +        if Shakapacker::Compiler.env["SHAKAPACKER_ASSET_HOST"].present?
I don't understand this part of the code. There should be a method to give the value.

Plus you repeated the long `Shakapacker::Compiler.env["SHAKAPACKER_ASSET_HOST"]`. WHY???

2023-10-27 02:43 UTC, justin808 commented on spec/backward_compatibility_specs/digest_strategy_spec.rb
> +    ENV["SHAKAPACKER_ASSET_HOST"] = nil
This is not the right way to stub envs.

2023-10-27 02:43 UTC, justin808 commented on spec/shakapacker/digest_strategy_spec.rb
> +    Shakapacker::Compiler.env["SHAKAPACKER_ASSET_HOST"] = "new-host"
why is the env method on the Compiler class?

2023-10-27 03:47 UTC, G-Rath commented
I think the problem here is that these are mincing config with env variables: `SHAKAPACKER_ASSET_HOST` gets set within a private instance method and the resulting `env` object is passed straight to `Open3.capture3` so there's no way you can access it from the digest strategies (aka `Shakapacker::Compiler.env["SHAKAPACKER_ASSET_HOST"]` will never work).

What they _do_ have is an instance of `Shakapacker::Configuration`, which feels like a suitable way to expose this anyway i.e. support `asset_host` within `shakapacker.yml` whose default value is `ActionController::Base.helpers.compute_asset_host` unless `SHAKAPACKER_ASSET_HOST` is set.

You should be able do that by adding this to `Shakapacker::Configuration`:

```
  def asset_host
    ENV.fetch("SHAKAPACKER_ASSET_HOST", fetch(:asset_host) || ActionController::Base.helpers.compute_asset_host)
  end
```

Then in the digest strategy and `Shakapacker::Compiler#webpack_env` you can do `config.asset_host`.

Also, I've not tested this but I'm pretty sure you can make this part of the digest returned by `watched_files_digest` rather than the filepath digest - I think that's nicer because it means those semantics are preserved and you also avoid growing the file name significantly which after a while will tend to annoy Windows.

2023-10-31 04:06 UTC, justin808 commented
this needs rebasing. I merged #374

2023-11-01 03:16 UTC, G-Rath commented on lib/shakapacker/digest_strategy.rb
> +        asset_host = Shakapacker.config.asset_host
can we try including this as part of the digest of the files themselves rather than the file path? that way the path will remain consistent and smaller, especially if in future there are other elements we decide we should be cachebusting on too

2023-11-01 19:12 UTC, G-Rath commented on README.md
> +**Note:**
fwiw imo this is a bug not a feature since its reasonable to assume given how `digest` works that changing the asset host would result in the digest changing, and as such doesn't require explicit documentation (similarly, I don't think it does for `mtime` either because that clearly says its based on timestamps only)

2023-11-03 18:53 UTC, justin808 commented on spec/backward_compatibility_specs/digest_strategy_spec.rb
> +    ENV["SHAKAPACKER_ASSET_HOST"] = nil
https://chat.openai.com/share/64cf0aa2-81dd-4cf2-b67a-ac54007d6bbe

2023-11-06 14:16 UTC, ahangarha commented on spec/backward_compatibility_specs/digest_strategy_spec.rb
> +    ENV["SHAKAPACKER_ASSET_HOST"] = nil
This is done in e43d164.

In another PR, many more tests should be updated for this. We never stubbed `ENV` in our tests.

2023-11-06 15:11 UTC, ahangarha commented on lib/shakapacker/digest_strategy.rb
> +        asset_host = Shakapacker.config.asset_host
This is a good point, and I will try to implement it.
Thanks for the suggestion.

2023-11-06 23:25 UTC, justin808 commented
@ahangarha please make changes suggested by @G-Rath!

2023-11-07 09:21 UTC, ahangarha commented
Regarding reviews:
- [x] Make asset_host changes affect the digest of the files rather than filenames [from this comment](https://github.com/shakacode/shakapacker/pull/364#discussion_r1378352191).
- [x] Update the changelog and list this PR as a fix instead of a new feature [from this comment](https://github.com/shakacode/shakapacker/pull/364#discussion_r1379204003).
- [ ] No change in this PR regarding [this comment](https://github.com/shakacode/shakapacker/pull/364#issuecomment-1782244368) since this should be done in another PR.

2023-11-07 09:36 UTC, justin808 commented on lib/shakapacker/digest_strategy.rb
> +        Digest::SHA1.hexdigest(file_ids.join("/").concat(asset_host))
@G-Rath is this what you had in mind?

2023-11-07 20:35 UTC, G-Rath requested changes
This is looking good to me, just needs the change to the readme removed and then should be good to go

2023-11-07 20:35 UTC, G-Rath commented on lib/shakapacker/digest_strategy.rb
> +        Digest::SHA1.hexdigest(file_ids.join("/").concat(asset_host))
Yup this looks good to me!

2023-11-23 02:15 UTC, justin808 approved these changes

2023-11-23 02:15 UTC, justin808 commented
LGTM

2023-11-23 02:46 UTC, G-Rath approved these changes
the readme change is still there, but happy to do a follow-up PR removing it instead of blocking this :)

2023-11-24 18:34 UTC, ahangarha commented
> the readme change is still there

Frankly, I don't know how that happened.
In any case, in resolving the merge conflict, I fixed this issue too.

2023-11-24 19:21 UTC, G-Rath commented on README.md
> +**Note:** If you want to enforce recompilation on asset host change (for example, through `SHAKAPACKER_ASSET_HOST` environment variable), in addition to using digest strategy, you should set `compile
@ahangarha this looks like a previous doc update that was since removed - I think it would probably be best to just do a brand new commit manually undoing the changes to the readme rather than trying to do `git revert` since everything will be squashed anyway

2023-11-24 21:32 UTC, G-Rath approved these changes

2023-11-24 21:32 UTC, ahangarha commented on README.md
> +**Note:** If you want to enforce recompilation on asset host change (for example, through `SHAKAPACKER_ASSET_HOST` environment variable), in addition to using digest strategy, you should set `compile
Well...
I removed it manually.
Finally... 🙂

2023-12-01 06:03 UTC, merged