Add asset_host and relative_url_path to config file
shakacode/shakapacker pull request #376
Opened 2023-11-07 14:14 UTC by ahangarha

### Summary

This is a follow-up PR, implementing what has been discussed [here](https://github.com/shakacode/shakapacker/pull/364#issuecomment-1782244368).

### Pull Request checklist

- [x] Add/update test to cover these changes
- [x] Update documentation
- [ ] Update CHANGELOG file

### Note
This PR is made on top of [make-compilation-stale-on-host-change](https://github.com/shakacode/shakapacker/tree/make-compilation-stale-on-host-change) branch and is supposed to get merged after the PR #364 merge.

### Concerns
- Do we actually use `relative_url_path`? It seems this is a leftover from some old feature which is now completely removed from Shakapacker. If so, we should remove it.

2023-11-17 00:55 UTC, justin808 commented
@G-Rath I think we just need one PR for all this work.

@ahangarha if @G-Rath agrees, please consolidate the comments into this PR and change the base to main/master.

2023-11-17 00:57 UTC, G-Rath commented
I think it's useful giving it a dedicated changelog entry because this is a feature whereas the other PR is a bug

2023-11-17 10:05 UTC, ahangarha commented
I initially aimed to add this to the previous PR but then I thought it better to keep it separate to make a decision about it independently.

Since this PR is on top of the #364 PR, I would propose merging that PR first and then merging this one.

2023-12-05 04:33 UTC, justin808 requested changes
Seems like we need 
1. Migration instructions
2. Updated README?

CC: @ahangarha @G-Rath

2023-12-05 04:33 UTC, justin808 commented on lib/shakapacker/configuration.rb
> -  def relative_url_root
Is this a public API?

Do we need docs explaining this change?

What is the migration if somebody used this ENV: `SHAKAPACKER_RELATIVE_URL_ROOT`.

Is this OK as a feature level bump?

@G-Rath @ahangarha

2023-12-05 07:35 UTC, ahangarha commented on lib/shakapacker/configuration.rb
> -  def relative_url_root
Sorry for not making it enough clear. I added more explanation in the commit message but it is not enough visible. So let's quote it here:

>  Remove any references to relative_url_root
> 
> Despite being added in webpacker, it never got used. There is no
> functionality tied to this configuration and this commit, removes its
> references in the code and tests.

and from my private discussion with Judah, he phrased it this way:

> Looks like `relative_url_root` was added by https://github.com/rails/webpacker/pull/1236, but instead of doing a follow-up PR to add the `relative_url_root` to the `publicPath`, they went with a `public_root` configuration instead (which `publicPath` does use) https://github.com/rails/webpacker/pull/1848
> 
> So relative_url_root looks to be dead code.
> 

So, we just inherited this extra unused configuration from Webpacker.
To my understanding, removing this shouldn't have any impact on any project (unless someone has made a customized `shakapacker` and used this configuration, but it is very unlikely.

I am not sure if we should keep carrying this code by deprecating it till the next major release. Mentioning this removal in the changelog wouldn't be bad (if needed).

2023-12-05 19:21 UTC, G-Rath commented on lib/shakapacker/configuration.rb
> -  def relative_url_root
hmm I'm not quite following, but I think if `relative_url_root` is just dead code that's otherwise not actually causing harm, I'd prefer leaving it alone in this PR and then dealing with it separately.

We'll want to do a v8 for switching to `package_json` provided that goes well which I'd personally like to have out within the next 6 months so assuming others are happy with that timeline, it should be pretty fine to slap a deprecation warning on `relative_url_root` knowing it won't be hanging around for much longer

2023-12-06 10:18 UTC, ahangarha commented on lib/shakapacker/configuration.rb
> -  def relative_url_root
That is also fine to me.

@justin808 I reverted the last commit (of removing `relative_url_root`).
We will handle the deprecation later.

If agreed, and there is no other required changes, we are good to go with merge and 7.2 release.

2023-12-06 18:08 UTC, G-Rath commented on lib/shakapacker/configuration.rb
> -  def relative_url_root
Is `relative_url_root` actually being used though? overall I think if the plan is to deprecate this, we shouldn't change it at all unless it's actually broken

2023-12-07 09:51 UTC, ahangarha commented on lib/shakapacker/configuration.rb
> -  def relative_url_root
Well, I agree with you. I don't see any good reason for introducing a new public interface to `Configuration` for a deprecated feature.

So I will narrow down this PR to only cover `asset_host` and not `relative_url_root`.

2023-12-07 11:35 UTC, ahangarha commented on lib/shakapacker/configuration.rb
> -  def relative_url_root
Well, the actual moving of the logic into the configuration was done in #374. This PR was to add some fixes and improve tests. The PR title is misleading.

So I think now that all usages of `relative_url_root` goes through a method in `Configuration`, that method is the right place for showing a deprecation message.

2023-12-18 16:03 UTC, ahangarha commented on lib/shakapacker/configuration.rb
>    end
The only concern with this PR is that I ensure the retuned value is a string in any case. This means if nothing is provided, we get `""` (empty string).

That time, I thought it could help with simplification so that could only check `asset_host.empty?`.

I just wanted to raise this again to ensure it is not missed out in the reviews.

2023-12-21 08:37 UTC, justin808 commented on lib/shakapacker/configuration.rb
> +      fetch(:asset_host) || ActionController::Base.helpers.compute_asset_host
how about `fetch(:asset_host).presence` to ensure not blank?

2023-12-21 08:37 UTC, justin808 commented on lib/shakapacker/configuration.rb
>    end
Ca fetch return a ""?

2023-12-21 08:37 UTC, justin808 commented on spec/backward_compatibility_specs/compiler_spec.rb
> +    expect(Webpacker.compiler.send(:webpack_env)["SHAKAPACKER_ASSET_HOST"]).to eq ""
This is weird.

2023-12-21 08:37 UTC, justin808 commented on spec/shakapacker/configuration_spec.rb
> +          it "returns an empty string" do
why empty strings and not nil?

2023-12-21 14:55 UTC, ahangarha commented on lib/shakapacker/configuration.rb
>    end
It can. Internally, it runs `fetch` on a hash. So it can potentially return `""` or `"   "`. Though it is very unlikely someone deliberately pass `key: ""` in the config file.

Should we consider this in fetch as kind of normalization to ensure we either get a meaningful value or nil? I cannot think of any scenario where in the config we want to pass `""` and not `nil`.

2023-12-21 15:23 UTC, ahangarha commented on spec/shakapacker/configuration_spec.rb
> +          it "returns an empty string" do
I think this was the logic when I was implementing these changes: while calculating [digest for the watched assets](https://github.com/shakacode/shakapacker/blob/bcc2fbc556c1ec767f1110e48473391c86ec713d/lib/shakapacker/digest_strategy.rb#L48-L49), I noticed that we may get `nil` and at that point, it was strange for me to get nil for `asset_host`. I either could convert `asset_host` to string to ensure in case of getting `nil`, we don't break the logic (for contamination). Later I thought it is better to get empty string right out of `asset_host` method if nothing is provided. (Though I forgot to remove the conversion to string in the mentioned code above).

Now I think it is better to return `nil` and handle `nil` when we want to use it. So I change these lines back to return nil and convert the value into string when we need it.

2023-12-21 15:30 UTC, ahangarha commented on spec/backward_compatibility_specs/compiler_spec.rb
> +    expect(Webpacker.compiler.send(:webpack_env)["SHAKAPACKER_ASSET_HOST"]).to eq ""
Back to `nil`

2023-12-22 21:06 UTC, justin808 commented on lib/shakapacker/configuration.rb
> +      fetch(:asset_host) || ActionController::Base.helpers.compute_asset_host
👍 but no change? why?

2023-12-22 21:16 UTC, merged