fix: `hmr: false` doesn't disable Hot Module Reloading
shakacode/shakapacker pull request #392
Opened 2023-12-22 14:47 UTC by thedanbob

### Summary

webpacker-dev-server >= 4 enables HMR by default, so explicitly disable when `hmr: false`. Fixes #390

### Pull Request checklist
_Remove this line after checking all the items here. If the item does not apply to the PR, both check it out and wrap it by `~`._

- [x] Add/update test to cover these changes
- [x] ~Update documentation~
- [ ] Update CHANGELOG file

2023-12-23 09:34 UTC, ahangarha requested changes
Thanks for the PR. I just made some suggestions. What do you think about them?

2023-12-23 09:34 UTC, ahangarha commented on lib/shakapacker/dev_server_runner.rb
> +        end
Since `webpack` enables `hmr` by default, we don't need to pass explicitly `--hot`. So I think we can simplify the logic, drop the `--hot` addition, and only add `only` or `--no-hot` as per the value of `@hot`. Something like

```rb
# We don't add `--hot` of `@hot == true` since it is the default behavior of webpack.
cmd << "--no-hot" unless @hot
cmd << "only" if @hot == "only"
```

I think adding the comment is good for providing context.

2023-12-23 09:34 UTC, ahangarha commented on spec/backward_compatibility_specs/dev_server_runner_spec.rb
> +        cmd = package_json.manager.native_exec_command("webpack", ["serve", "--config", "#{test_app_path}/config/webpack/webpack.config.js", "--no-hot", "--quiet"])
I wonder if we should change the configuration file and set `hmr: true`. It helps to keep the tests cleaner and more focused. It is weird to have `--no-hot` on so many tests.

@justin808 What do you think?

Also, I can think of it as a separate PR.

2023-12-23 23:36 UTC, thedanbob commented on lib/shakapacker/dev_server_runner.rb
> +        end
Makes sense, I've made this change in a slightly different way.

2023-12-24 05:49 UTC, justin808 commented
@thedanbob can I get a link to the docs or source code of the '--no-hot' option?

2023-12-24 07:51 UTC, ahangarha commented
@justin808 
In the readme of the `webpack-dev-server`, [it is mentioned](https://github.com/webpack/webpack-dev-server/blob/540c43852ea33f9cb18820e1cef05d5ddb86cc3e/README.md?plain=1#L133).

 Apart from that, all of the options in webpack CLI can be reverted by using `no` prefix. This is why no explicit reference or implementation of `--no-hot` exists in the code base. `--no-hot` is simply the opposite of `--hot`, so it sets `hot` to false.

2023-12-24 14:37 UTC, thedanbob commented
@justin808 I just checked and this would work as well, and is perhaps cleaner:
```ruby
cmd += ["--hot", (@hot || false).to_s] if @hot != true
```

Of course I'll have to adjust the tests to match. Probably making the default (in the tests) as `hmr: true` would be best, as @ahangarha suggested.

2023-12-24 15:30 UTC, ahangarha commented
@thedanbob 
> `cmd += ["--hot", (@hot || false).to_s] if @hot != true`

I prefer a more visible code in more lines over one-liners. It is simpler to read, understand, and debug.

2023-12-24 16:46 UTC, thedanbob commented
How does this look? I went ahead and changed the tests to use `hmr: true`. My implementation did have a side effect on a couple of `inlining_css` tests but I think the behavior change is unimportant?

2023-12-24 18:00 UTC, ahangarha requested changes
Thanks for the updates. I Shared my concerns in the comments.

2023-12-24 18:00 UTC, ahangarha commented on lib/shakapacker/dev_server_runner.rb
> +        @hot               = dev_server.hmr? || false
Should we use `false` as the fallback value for `@hot`? Doesn't seem right to me.

2023-12-24 18:00 UTC, ahangarha commented on lib/shakapacker/dev_server_runner.rb
> +        cmd += ["--hot", @hot.to_s] if @hot != true
If `@hot` is `false`, `cmd` becomes `[..., "--hot", "false",...]` which is wrong. It is also wrong with `nil` value because it adds `""` to the list. Some commands are sensitive about getting blank options.


I would propose using typical `if` conditions for explicit values (`true`, `false, `only`).

2023-12-24 18:35 UTC, thedanbob commented on lib/shakapacker/dev_server_runner.rb
> +        @hot               = dev_server.hmr? || false
This was to accommodate the logic below

2023-12-24 18:38 UTC, thedanbob commented on lib/shakapacker/dev_server_runner.rb
> +        cmd += ["--hot", @hot.to_s] if @hot != true
`--hot false` actually does work according to my testing, but perhaps it's not guaranteed to work in the future. Adding a default value of `false` above was to ensure `@hot` wouldn't be nil here. But I'll change it back to use `--no-hot`.

2023-12-24 22:22 UTC, ahangarha approved these changes
Looks good to me.
Thanks.

2023-12-29 07:32 UTC, merged

2023-12-29 07:32 UTC, justin808 commented
Thanks @thedanbob!