Strip additional_paths from the asset paths generated in the file.js rule
shakacode/shakapacker pull request #403
Opened 2024-01-09 16:53 UTC by paypro-leon

### Summary

#283 caused the top dir to be no longer stripped in the `file.js` rule. This exposes too much of the paths when `additional_paths` are used for assets within these paths.

For example when setting `additional_paths` like `app/assets` and with an asset at `app/assets/images/image.svg` would get a path like this `static/app/assets/images/image.svg`

In this PR the path will be `static/images/image.svg`

### Pull Request checklist

- [ ] Add/update test to cover these changes
- [ ] Update documentation
- [ ] Update CHANGELOG file

### Other Information

The `source_path` and `additional_paths` where often used together, so I added `includePaths` in the config which can be used in all these cases.

2024-01-10 04:32 UTC, justin808 commented
Can you please add:

1. Changes to README or other docs
2. Tests

2024-01-10 09:40 UTC, paypro-leon commented
@justin808 I didn't find any documentation about stripping the paths in the `file.js` rule. Do we want to add this somewhere in the `README`?

I added a test case to [package/rules/__tests__/file.js](https://github.com/shakacode/shakapacker/pull/403/files#diff-31dc147861a84dd998b67448efeebbe070831a5469156ec726a9a52fccb6af42) or would you like to add more?

2024-01-15 08:02 UTC, justin808 commented
> @justin808 I didn't find any documentation about stripping the paths in the `file.js` rule. Do we want to add this somewhere in the `README`?
> 
> I added a test case to [package/rules/**tests**/file.js](https://github.com/shakacode/shakapacker/pull/403/files#diff-31dc147861a84dd998b67448efeebbe070831a5469156ec726a9a52fccb6af42) or would you like to add more?

Thanks for the tests!

Yes, a few docs would be **AWESOME**. Thanks!

2024-01-19 15:41 UTC, paypro-leon commented
@justin808 I have added a mention of this change in the `README`

2024-01-20 02:23 UTC, justin808 commented
Is this a breaking change? 

Let's get some people to try this out and confirm it's not breaking:
https://rubygems.org/gems/shakapacker/versions/7.3.0.beta.1

Otherwise, I need to bump the major version.

@G-Rath @tomdracz @ahangarha @Judahmeek

2024-01-20 21:23 UTC, G-Rath commented
If I'm understanding this correctly, I don't think the introduction of `includePaths` is required and while it might be useful that change looks to be the result of a lot of the diff - I think it would be best if you reverted that for now, and open a dedicated issue if you want to make a case for it.

As for if this is breaking, I think that depends on the intended purpose of `additional_paths`: I've not ever used it and so far my attempts at trying to use it are giving errors. If the intent is to effectively include additional assets as if they were directly compiled by Shakapacker then I'd say this is probably a bug especially if these paths are mostly automated (i.e. apps should not require any changes after updating to continue working as normal, even if maybe a few caches are busted due to a slight url change)

But lets get the `includePaths` stuff reverted first and go from there

2024-01-21 13:44 UTC, ahangarha commented
I agree with @G-Rath regarding changing our configuration and replacing some entries with `includePaths`. I don't think the benefit of this change justifies introducing such a breaking change in the project. It is also not contributing to this particular PR. It is a separate thing and can be discussed and possibly implemented in a separate issue and PR.

Regarding the key change of this PR, I don't think it would break anything except in a project that has a separate part that depends on a very specific asset URL.

To be in a safe margin, I propose we make this feature optional for version 7 and mention in our documentation that this behavior will be permanent in our next major release. And to activate this feature, we may choose one the following:
- a new temporary configuration in `config/shakapacker.yml` that will be removed in version 8.
- an env variable like `SHAKAPACKER_STRIP_ADDITIONAL_PATH`.

We can keep it experimental in version 7 and default in version 8.

2024-01-22 10:45 UTC, paypro-leon commented
@G-Rath @ahangarha I reverted the `includePath` changes and made the change `opt-in` by setting `SHAKAPACKER_STRIP_ADDITIONAL_PATH`. Adding it to `config/shakapacker.yml` would introduce a change to the `Config` interface just like with `includePath` so this feels like the least intrusive change.

2024-01-22 17:22 UTC, G-Rath requested changes

2024-01-22 17:22 UTC, G-Rath commented on package/rules/file.js
> +      const stripPaths = process.env.SHAKAPACKER_STRIP_ADDITIONAL_PATHS === 'true' ? [...additionalPaths, sourcePath] : [sourcePath]
we might as well pull this from `shakapacker.yml` since we're accessing that already, and then it'll be easier to ensure its set consistency

2024-01-22 17:22 UTC, G-Rath commented on package/rules/less.js
> +          ]
nit: could you revert this?

```suggestion
          paths: [path.resolve(__dirname, 'node_modules'), sourcePath, ...paths]
```

2024-01-23 09:48 UTC, paypro-leon commented on package/rules/file.js
> +      const stripPaths = process.env.SHAKAPACKER_STRIP_ADDITIONAL_PATHS === 'true' ? [...additionalPaths, sourcePath] : [sourcePath]
While I agree it will be easier to use `shakapacker.yml` would that not result in more config? I think we should be careful adding more to `shakapacker.yml` file, especially if this is going to be temporary.

Maybe we should choose if this is going to be configurable option or just default behavior. Based on that we can decide what the best place for this should be. I leave the final decision to you guys and will change it accordingly.

2024-01-26 20:50 UTC, G-Rath commented on package/rules/file.js
> +      const stripPaths = process.env.SHAKAPACKER_STRIP_ADDITIONAL_PATHS === 'true' ? [...additionalPaths, sourcePath] : [sourcePath]
The "more config" is already being added by introducing an env variable, it's just harder to use - pulling it from `shakapacker.yml` means applications that use this can ensure it's _always_ enabled properly which is a lot harder to do with an env variable.

What you're referring to is actually a seperate but very good question - what is the long term plan for this? Personally I'd feel better discussing that without external metrics if I had a sample app that actually used additional paths so I can see the different behaviors in action.

I would say if no one currently has strong feels to why this _shouldn't_ be the new default behaviour then we should tie this new config variable with a message that shows at least when its not set (and maybe if it's set to false?) saying "hey we're planning to make this the default in the next major unless anyone objects - you should opt in to it now by setting <config variable>; please open an issue if this doesn't work or breaks your app or ... etc".

While it might seem verbose, I think it's very reasonable in this kind of situation since ultimately we can't not make improvements and also can't know about the requirements of all the applications out there so it's to users to report back about their use cases 🤷

2024-01-27 11:47 UTC, ahangarha commented on package/rules/file.js
> +      const stripPaths = process.env.SHAKAPACKER_STRIP_ADDITIONAL_PATHS === 'true' ? [...additionalPaths, sourcePath] : [sourcePath]
I think it is better to have minimum temporary changes in our config for an experimental feature. We should remove them in our next major release so better to keep it on the side, and just give a way for activating it.

But this is my thought. The decision is not technical (all options are possible) but a PM one.

@justin808 What do you think about how to incorporate this feature in this version and then in v8?

2024-03-14 17:45 UTC, paypro-leon commented on package/rules/file.js
> +      const stripPaths = process.env.SHAKAPACKER_STRIP_ADDITIONAL_PATHS === 'true' ? [...additionalPaths, sourcePath] : [sourcePath]
@justin808 @G-Rath @ahangarha @tomdracz Has any decision been made if this is going to be added? I personally don't mind either option. Lets choose one and I will update the PR.

2024-03-23 00:40 UTC, justin808 commented
@G-Rath should this PR be changed to be on the v8 branch?

2024-03-23 00:47 UTC, G-Rath commented
@justin808 I think first more investigation is needed to decide what should happen - I personally don't have much experience with this part of Shakapacker and so far have not been able to produce any notable difference in behaviour when trying to change the general settings to begin with.

If someone were to create a sample app that enabled exploring behaviours with different values that would at least help me to form an opinion on what I think we should do here.

As it is now though I've not seen a lot of activity to indicate this is a pressing issue so I don't think it should delay the release of v8

2024-03-23 10:32 UTC, tomdracz commented
@G-Rath Repro here: https://github.com/tomdracz/shakapacker-css-test/commit/1f2e367e83ac177a79a1c8371ac2f41d7affa837

I've added additional paths directory with one svg file and another svg file in main directory.

```
import 'images/test_additional.svg'
require.context('../images', true);
```

in pack js makes it so the relevant entries are pulled into manifest. `images/test_additional.svg` is resolved as we're looking into `additional_paths` when resolving imports.

In manifest though, they end up like below:
```
  "static/app/assets/images/test_additional.svg": "/packs/static/app/assets/images/test_additional-7a96f819dc16a03ee8e8.svg",
  "static/images/test.svg": "/packs/static/images/test-7a96f819dc16a03ee8e8.svg",
```

That additional path not being stripped, means the SVG from additional directory needs to be references as:
```
<%= image_pack_tag('app/assets/images/test_additional.svg') %>
```

I think removing that `app/assets` from output is sensible here as that just indicates entry directory (but `images` or anything further below that in hierarchy should be retained)

2024-03-23 18:06 UTC, G-Rath commented
@tomdracz thanks for that, I agree we should be stripping out the additional paths prefix out of the box.

@paypro-leon do you have the bandwidth to rebase this onto `next` and remove the option? otherwise me or @tomdracz can pick it up

2024-03-24 10:03 UTC, tomdracz commented
Since we're looking to lend this in v8, I would say let's just shop without option to opt-in/out and just mark as breaking change. The new handling is reasonable to be default and can't see compelling reason to specifically opt-out 🤔

2024-03-26 09:10 UTC, paypro-leon commented
@G-Rath I can pick it up and will remove the option.

2024-03-26 11:30 UTC, paypro-leon commented
Not sure why the jobs fails. Can we rerun the action manually or do I need to create a new commit?

2024-03-26 12:56 UTC, tomdracz approved these changes

2024-03-26 12:56 UTC, tomdracz commented
Rerun kicked in, LGTM. Thanks @paypro-leon !

2024-03-26 12:56 UTC, merged