test: update how Selenium is configured
shakacode/shakapacker pull request #457
Opened 2024-04-04 18:17 UTC by G-Rath

### Summary

This updates how Selenium is configured so that the dummy specs can be run locally in more environments such as Ubuntu on WSLv2.

### Pull Request checklist
_Remove this line after checking all the items here. If the item does not apply to the PR, both check it out and wrap it by `~`._

- [x] Add/update test to cover these changes
- [x] ~Update documentation~
- [x] ~Update CHANGELOG file~

### Other Information

I think this is just the result of the dummy project being generated a long time ago and so this is effectively just updating the config based on changes that have happened over the years - specifically this was based on the [config we generate](https://github.com/ackama/rails-template/blob/main/variants/backend-base/spec/rails_helper.rb) in our `rails-template`.

Before this is landed someone should try this locally to ensure this doesn't just "work on my machine" - until then I'll mark this as a draft.

2024-04-05 10:07 UTC, tomdracz requested changes

2024-04-05 10:07 UTC, tomdracz commented on spec/dummy/spec/rails_helper.rb
>      driven_by driver
@G-Rath Tested this locally and it's failing 😅 Pretty sure it's that line here. After removals we are ending with nil so defaulting back to whatever driver is default 🤔 With the addition as suggestion below it does seem to work as expected though

```suggestion
    driven_by :selenium_chrome
```

2024-04-05 19:00 UTC, G-Rath commented on spec/dummy/spec/rails_helper.rb
>      driven_by driver
Ironically I'm pretty sure that's the most problematic:

```
2024-04-06 07:54:25 INFO Selenium [:logger_info] Details on how to use and modify Selenium logger:
  https://selenium.dev/documentation/webdriver/troubleshooting/logging

2024-04-06 07:54:25 WARN Selenium [:selenium_manager] The version of chrome cannot be detected. Trying with latest driver version
2024-04-06 07:54:26 WARN Selenium [:selenium_manager] The version of chrome cannot be detected. Trying with latest driver version
F2024-04-06 07:54:26 WARN Selenium [:selenium_manager] The version of chrome cannot be detected. Trying with latest driver version
2024-04-06 07:54:27 WARN Selenium [:selenium_manager] The version of chrome cannot be detected. Trying with latest driver version
F

Failures:

  1) hello_world loads correct view
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: visit "/hello_world"

          Selenium::WebDriver::Error::UnknownError:
            unknown error: cannot find Chrome binary
```

I'll do some more digging - for context, WSL (Windows Subsystem for Linux) runs an integrated terminal-based VM within Windows which nowdays ships with WSLg by default so you can run GUIs natively alongside Windows apps; I've been able to run both headless and headful browser based tests with RSpec without major issue though I already know it doesn't work in all cases but at this point I think that's more a configuration thing then WSL itself.

i.e. with apps generated with our [`rails-template`](https://github.com/ackama/rails-template) I can run standard heavy tests, but our lighthouse accessibility and performance based tests which uses [`lighthouse-matchers`](https://github.com/ackama/lighthouse-matchers) fail

2024-04-06 07:32 UTC, tomdracz commented on spec/dummy/spec/rails_helper.rb
>      driven_by driver
Interesting. On my end without this change, the JS specs were falling as there was nothing executing JS. If they passed on your end, then I wonder what is running that 🤔

2024-04-06 18:57 UTC, G-Rath commented on spec/dummy/spec/rails_helper.rb
>      driven_by driver
Ok apparently I've just been silly - updating `selenium-webdriver` was the real fix, because they introduced the webdriver autofinding logic in ~4.15+ and I was using 4.10 🤷

2024-04-06 18:57 UTC, closed without merging

2024-04-08 14:48 UTC, ahangarha commented
This issue of version mismatch is really annoying.