WIP: Ensure consistent versions of package and gem
shakacode/shakapacker pull request #51
Opened 2022-02-05 11:49 UTC by tomdracz

⚠️ WIP ⚠️ 

Closes #36 

- Adds version check to ensure consistency between gem and npm package versions (mostly adapter from https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/version_checker.rb)
- Updates instructions and generators to use bundler `--strict` and yarn `--exact` flags to lock versions.

TODO:

- [ ] Add tests for the `VersionChecker` module

2022-02-05 11:49 UTC, tomdracz commented on lib/webpacker/railtie.rb
> +  initializer "webpacker.version_checker" do
Is there a better place for this to run?

2022-02-05 11:51 UTC, tomdracz commented
@justin808 Still need to add tests, but functionality is there. Can you take a peek and let me know if that's what you had in mind?

2022-02-05 12:05 UTC, tomdracz commented on lib/webpacker/version_checker.rb
> +        msg = "**ERROR** Webpacker: Webpacker gem and node package versions do not match\n#{common_error_msg}"
Are raises bit heavy handed? Maybe raise in test and dev env and warn otherwise?

2022-02-06 05:55 UTC, justin808 commented on lib/webpacker/version_checker.rb
> +        msg = "**ERROR** Webpacker: Webpacker gem and node package versions do not match\n#{common_error_msg}"
Let's think through this. Somebody merges one of those dependabot updates only for the gem. CI fails if there are any tests. 

But what if there is no CI?

Should we just warn?

And what if someone is using only the view helpers?

2022-02-06 06:55 UTC, justin808 approved these changes
@tomdracz  Would be awesome to have a few tests if you have time. LGTM.

2022-02-06 06:55 UTC, justin808 commented on lib/webpacker/railtie.rb
> +  initializer "webpacker.version_checker" do
Seems OK.

2022-02-07 23:06 UTC, tomdracz commented
@justin808 Tests are in. CI fails on Rubocop because of Gemfile.lock. Will be back in business when https://github.com/shakacode/shakapacker/pull/59 is merged

2022-02-08 09:03 UTC, justin808 commented
@tomdracz I'd like this to be opt-in since it's feasible that one could use the view helpers without the JS package.

I think the option should be in the webpacker.yml file.

2022-02-08 10:05 UTC, tomdracz commented
@justin808 The check is skipped if there's no package but yeah, opt-in will be nice and it stops this being a breaking change. Will amend

2022-02-08 23:02 UTC, justin808 requested changes
Nice job on the tests.

I think can we can distinguish false from missing. See the comments.

2022-02-08 23:02 UTC, justin808 commented on lib/install/config/webpacker.yml
> +  ensure_consistent_versioning: false
Default for new installs should be true.

I think if this attribute is not in the webpacker.yml file, then we can use false.

2022-02-08 23:02 UTC, justin808 commented on lib/webpacker/configuration.rb
> +    fetch(:ensure_consistent_versioning)
Does this throw if not defined?

I think we can have a default of false, otherwise, use the value in the config, and change the config template to be true.

2022-02-08 23:41 UTC, tomdracz commented on lib/webpacker/configuration.rb
> +    fetch(:ensure_consistent_versioning)
@justin80 this won't throw. Worst case scenario is that it would be nil if neither app webpacker.yml or default one didn't have the key.

This does make it tricky for new installs to default to true - we'd be essentially defaulting that value for anyone who hasn't updated their webpacker.yml to opt out.

I think our options are:
- default to false and change to true in next major release
- Leave default of false and intercept/amend this during the install
- amend config fetch for this one option to remove lookup in default config if option is not defined in app webpacker.yml

Second option feels bit convoluted and meh.
Third one is easy to do, but I'm not a fan of diverging behaviour. I feel if that was the way to go, I'd be looking to remove this band aid in the next major release.

Lemme know what you think

2022-02-08 23:50 UTC, justin808 commented on lib/webpacker/configuration.rb
> +    fetch(:ensure_consistent_versioning)
OK, we'll go with:

> default to false and change to true in next major release

Can we print a message then to suggest adding this, so long as the npm package is installed?

2022-02-08 23:59 UTC, tomdracz commented on lib/webpacker/configuration.rb
> +    fetch(:ensure_consistent_versioning)
Sure, message will work. I'll sort this out in a next day or two 👍

2022-02-11 16:05 UTC, tomdracz commented
@justin808 I've added some warning messages printed if the check is disabled. Can you take a peek?

2022-02-14 03:40 UTC, justin808 commented
@tomdracz Looks good. Shall I merge and release?

2022-02-14 08:21 UTC, tomdracz commented
Let's do it @justin808 !

2022-02-20 05:16 UTC, justin808 commented
@tomdracz as soon as you resolve conflicts, I'll merge.

2022-02-21 09:12 UTC, tomdracz commented
@justin808 Conflicts resolved

2022-02-21 09:30 UTC, merged

2022-02-21 09:30 UTC, justin808 commented
Thanks, @tomdracz!